### ISSUE TITLE
Lack of contributing.md files in your project

### ISSUE THREAD

**Issue by rishyym0927** [GDSC-RCCIIT/gdg-website#1]
Hey can you assign this issue and label it under gssoc-ext level 1

**Comment by rishicds** [comment]
@rishyym0927  assigned

**Comment by tarunkumar2005** [comment]
@rishicds I can see the issue is open for 2 weeks and still not fixed so assign this to me i will work on this issue.

**Comment by rishicds** [comment]
@tarunkumar2005 assigning you
