### ISSUE TITLE
[Enhancement]: Add animations to Landing Page

### ISSUE THREAD

**Issue by inkerton** [GDSC-RCCIIT/gdg-website#101]
![image](https://github.com/user-attachments/assets/a88cae18-b1eb-42df-bcc9-a6db39145e1f)

@rishicds I have made 3 PRs for all 3 issues. You can assign this to me after you have reviewed all 3 PRs.

**Comment by rishicds** [comment]
Hi, please finish #96 #97 #98 then I'll assign these three

**Comment by rishicds** [comment]
assigned
