### ISSUE TITLE
Issues Caused by Merging PR #98 | UI Fixes in Projects Page | Variable Length of Containers

### ISSUE THREAD

**Issue by Shariq2003** [GDSC-RCCIIT/gdg-website#112]
### Fixes

After the merging of the PR #98 by @inkerton, the project containers are set to variable heights, that disturbs the UX and UI.

### Differences : Comparision of the Main Branch and My projects page Branch

![image](https://github.com/user-attachments/assets/8b0c5086-e7c1-44f7-9251-731df5e4a7cc)

Last merge by @Inkertion 's PR into main that changes the projects page.

### Video Diff

https://github.com/user-attachments/assets/8d57181c-1810-4a83-b097-d0d241509382

@rishicds assign this to me.

**Comment by rishicds** [comment]
Assigned
