### ISSUE TITLE
Adding backend schemas in mongodb for users, events and teams

### ISSUE THREAD

**Issue by J-B-Mugundh** [GDSC-RCCIIT/gdg-website#117]
I would like to add the mongodb schema for users (with role based access - admin, leads, users), events and teams. 

### Additional information: 

Post this issue, I would like to create issues for 

- Adding routes and integrating login signup with users schema
- Google sign in integration
- A CRUD page for events with backend integration
- A CRUD page for teams with backend integration

Please let me know your suggestions on this.

**Comment by J-B-Mugundh** [comment]
@rishicds please assign me the issues and let me know your suggestions or concerns in case you have any.

**Comment by rishicds** [comment]
hi sorry, but we currently havent decided on the backend, so i havent assigned
