### ISSUE TITLE
Improving the home page UI completely and adding more relevant content to make GDSC-RCCIIT stand out from rest of the others. 

### ISSUE THREAD

**Issue by J-B-Mugundh** [GDSC-RCCIIT/gdg-website#118]
Improving the home page UI completely and adding more relevant content to make GDSC-RCCIIT stand out from rest of the others.

**Comment by J-B-Mugundh** [comment]
@rishicds please assign me the issues and let me know your suggestions or concerns in case you have any.

**Comment by rishicds** [comment]
assigned,
