### ISSUE TITLE
Feature : Footer Enhancement 

### ISSUE THREAD

**Issue by dev129** [GDSC-RCCIIT/gdg-website#120]
Hi @rishicds,

I’d like to propose an important enhancement to the GDG RCIIT website regarding the footer design. A well-structured footer is crucial for improving user experience, and integrating the newsletter subscription directly within the footer can streamline navigation and reduce clutter.

### Importance of a Well-Structured Footer:

1. **Improved User Experience**: A concise and organized footer can provide users with easy access to essential information, enhancing their overall experience on the site.

2. **Integrated Newsletter Subscription**: By including a newsletter subscription directly in the footer, we eliminate the need for a separate section. This not only saves space but also encourages more users to subscribe, as they can do so seamlessly while browsing.

3. **Increased Engagement**: A well-designed footer with subscription options can drive higher engagement rates. Users are more likely to subscribe when it’s easily accessible without navigating away from their current page.

4. **Branding and Information**: The footer is an excellent place to reinforce our branding and provide necessary information, such as contact details, social media links, and quick access to important pages.

I believe these enhancements will significantly benefit our website and align with our goals for user engagement and satisfaction. I look forward to discussing this further.

**Comment by rishicds** [comment]
assigned

**Comment by dev129** [comment]
![image](https://github.com/user-attachments/assets/7082928e-f82f-4c54-bfea-c95856efb724)
Upgraded footer level.

**Comment by rishicds** [comment]
hi yes this looks great, you can create a PR for this, just make sure you are on the latest version as a lot of changes have been added since then! Good job!

**Comment by dev129** [comment]
Yeah, I am just waiting for everything to start work well first.
