### ISSUE TITLE
Feature: Landing Page enhancement

### ISSUE THREAD

**Issue by dev129** [GDSC-RCCIIT/gdg-website#122]
Subject: Proposal for Landing Page Enhancement and Updates

Hi @rishicds,

I’d like to address a couple of important issues regarding the GDG RCIIT website, specifically the landing page layout and the content updates for events and projects.

### 1. Landing Page Enhancement:

Currently, the event and project sections on the landing page are horizontally stacked, which may not provide the best visual appeal or user experience. I can easily reformat this section to display the stacks horizontally, making the layout more engaging and modern.

### 2. Updating Events and Projects:

Additionally, I’ve noticed that the events and projects by GDSC RCIIT have not been updated. Keeping this information current is essential for user engagement and transparency. I can take care of these updates to ensure that our community stays informed about our latest activities.

By addressing these issues, we can significantly improve the website’s functionality and user experience. I look forward to your feedback on these proposals.

![image](https://github.com/user-attachments/assets/a51e2985-c028-446b-a20d-ef6985ff5332)

I can make it look better.

**Comment by Shariq2003** [comment]
@dev129  update your forked repo

**Comment by dev129** [comment]
@Shariq2003 I have updated that even before running the server but this is what I saw .

**Comment by Shariq2003** [comment]
> @Shariq2003 I have updated that even before running the server but this is what I saw .

No bro

**Comment by Shariq2003** [comment]
You have to update the forked repo, then take a pull from main into your local main repo

**Comment by dev129** [comment]
Oh ok , thanks @Shariq2003 , also how are you doing so many PR and managing everything so swiftly ?

**Comment by Shariq2003** [comment]
> Oh ok , thanks @Shariq2003 , also how are you doing so many PR and managing everything so swiftly ?

Bro, actually I have continuously worked from the start and given almost 15-20 hrs, as a result currently suffering from bad health due to bad sleep cycle and now you can see that my contributions getting down since 2 days.
😥

**Comment by dev129** [comment]
Bro you are on 2nd position! What more is needed (I still am on trailblazer) also itne ideas , itne contributions, itna time dena thinking ke liye, and then here's me with no idea on how and what to contribute to ?
