### ISSUE TITLE
Uniform website theme

### ISSUE THREAD

**Issue by dev129** [GDSC-RCCIIT/gdg-website#123]
Hi @rishicds 

**Description:**
The current website theme lacks uniformity across various pages, leading to significant inconsistencies in design elements and overall user experience. 

**Importance:**
1. **User Experience (UX):** A cohesive theme enhances navigation and usability, allowing users to intuitively understand how to interact with the site. Inconsistencies can frustrate users and lead to higher bounce rates.

2. **Brand Identity:** A uniform theme reinforces brand identity and professionalism. When users encounter a disjointed design, it can create confusion about the brand’s credibility and values.

3. **Accessibility:** Consistent design practices improve accessibility for all users, including those with disabilities. A standardized layout can make it easier for assistive technologies to interpret content.

4. **Conversion Rates:** A well-designed, uniform theme can lead to higher conversion rates. When users feel comfortable and confident in navigating the site, they are more likely to engage and complete desired actions.

**Recommendation:**
It’s crucial to prioritize the development of a consistent theme across the website. This should involve a review of design elements, adherence to brand guidelines, and user testing to ensure a seamless experience.

**Priority:** Critical

**Comment by rishicds** [comment]
assiggned
