### ISSUE TITLE
Adding Content(Roadmap) to C++ Learning Track

### ISSUE THREAD

**Issue by pratheekv39** [GDSC-RCCIIT/gdg-website#124]
I would love to contribute to C++ Learning Track in the Resources Section . I would love to create a Roadmap for that section . 
@rishicds Can you assign it to me and provide me suggestions on how to approach it ( If you guys have any particular format or Guidelines) . 
Cheers :)

**Comment by rishicds** [comment]
assigned, all the best

**Comment by rishicds** [comment]
you can create the page like this
1. Introduction
2. Example
3. Roadmap
4. Resources(Text or Video)
5. Quiz/Projects

Since you are in the C++ learning track I recommend adding websites where users can practice coding

**Comment by pratheekv39** [comment]
<img width="713" alt="image" src="https://github.com/user-attachments/assets/8ca03535-36f3-4a0f-8c92-d53cb10358ab">
@rishicds Can you help me out , after syncing the project with the latest code, this error pops up even after setting everything up correctly

**Comment by pratheekv39** [comment]
@rishicds Nevermind , it is solved now . Thanks for fixing the bug . I will work on it now ....

**Comment by rishicds** [comment]
Yes we reverted the changes which caused - this you can staet working
