### ISSUE TITLE
[UI Addition]: Make a responsive footer

### ISSUE THREAD

**Issue by inkerton** [GDSC-RCCIIT/gdg-website#13]
I am making a general responsive footer for now . I will make changes as per you require.

@rishicds Kindly assign it to me under gssoc

**Comment by inkerton** [comment]
@rishicds Please checkout the PRs and merge them according to the number or else they might give error

**Comment by rishicds** [comment]
already in #3, if he doesnt give any pr in 3 days Ill checkout yours

**Comment by inkerton** [comment]
@rishicds Well the issue was created a week before and there was no PR done till today also I made a PR before he did on the same day as I opened the issue.

Well I might think I was free to work on the project. 3 of my issues and PRs will be wasted and I'll have to wait more can't you ask him to work on top of my PR. He is already past his limit. I would like to work further than sit idle and wait.
