### ISSUE TITLE
Dynamic Event Calendar

### ISSUE THREAD

**Issue by amitb0ra** [GDSC-RCCIIT/gdg-website#138]
We would like to implement a **Dynamic Event Calendar** feature on the GDG RCCIIT website. This calendar will showcase all upcoming events and allow users to filter events by type (e.g., workshop, talk, hackathon). Users should also have the ability to RSVP directly from the calendar interface.

- Display a calendar view of upcoming events.
  - Workshops
  - Talks
  - Hackathons
  
  **Please assign me under GSSoC'24 ext and hacktoberfest labels**

**Comment by rishicds** [comment]
assigned
