### ISSUE TITLE
[UI Enhancement]: Revamp the margins and footings of hackathon Page and also add badges

### ISSUE THREAD

**Issue by inkerton** [GDSC-RCCIIT/gdg-website#146]
![image](https://github.com/user-attachments/assets/0a6bbf57-a76c-4a87-9142-dced1e96e8f6)

![image](https://github.com/user-attachments/assets/1247480d-71f2-4bdd-bddb-b82ef1049006)

The scaleing transition of on hover is not right also the paddings and margins.
I can also add a status badge stating whether the hackathon is currently ongoing, planned, or finished.
An opening and closing date for registraion for planned hackathons.
For finished, a view button. and for ongoing a 'results will be declared on' date.

**Comment by inkerton** [comment]
@rishicds Can You assign this to me after you have a look at my previous PRs.

**Comment by rishicds** [comment]
assigned
