### ISSUE TITLE
[Feature]: Hackathon Details Page

### ISSUE THREAD

**Issue by inkerton** [GDSC-RCCIIT/gdg-website#147]
![image](https://github.com/user-attachments/assets/0a6bbf57-a76c-4a87-9142-dced1e96e8f6)

![image](https://github.com/user-attachments/assets/1247480d-71f2-4bdd-bddb-b82ef1049006)

It would display the necessary info, eligibility, dates.
Some rules and regulations normally followed during hackathons. 
Images for past hackathons.
For ongoing ones a quote to motivate them .
And for upcoming ones tentative dates.

**Comment by inkerton** [comment]
@rishicds Please assign this to me too

**Comment by rishicds** [comment]
assigned

**Comment by rishicds** [comment]
if you want you can add a page where gdg team members would be able to add/delete hackathons, you can make this a seperate PR, you dont have to add any type of auth just make the page

**Comment by inkerton** [comment]
ok I will do it
