### ISSUE TITLE
CICD Workflows for Task automation (PLEASE READ DESC. IT IS REALLY HELPFUL)

### ISSUE THREAD

**Issue by shubhagarwal1** [GDSC-RCCIIT/gdg-website#151]
**Workflow to be implemeted**

- Auto Comment on Issue
- Auto Comment on PR
- Auto Comment on PR Merge
- Auto Label Issues
- Auto Label PRs
- Close Issues on PR Merge
- Comment on Issue Close

**Comment by rishicds** [comment]
assigned, all the best!
