### ISSUE TITLE
ADD Connect with local developers Page

### ISSUE THREAD

**Issue by shubhagarwal1** [GDSC-RCCIIT/gdg-website#152]
ref
<img width="1440" alt="Screenshot 2024-10-25 at 5 22 39 AM" src="https://github.com/user-attachments/assets/728a49c4-5764-437b-b366-5999f79246fd">

**Comment by rishicds** [comment]
assigned

**Comment by shubhagarwal1** [comment]
> assigned

Hey rishi can we connect on discord ?
