### ISSUE TITLE
[Feature]: Add hackathon for amin panel

### ISSUE THREAD

**Issue by inkerton** [GDSC-RCCIIT/gdg-website#167]
Add hackathons for admin panel as required. They will contain 

### Basic Information
* **Hackathon Title:** A clear and concise title that reflects the theme or focus of the event.
* **Date and Time:** Start and end dates and times of the hackathon, including any specific time zones.
* **Duration:** The total duration of the hackathon.
* **Location:** The physical location (if applicable) or the platform where the hackathon will be held (e.g., online, virtual).
* **Theme:** The specific theme or problem statement that participants will address.
* **Eligibility:** The criteria for participation, including age limits, academic level, and any specific requirements.

### Registration and Participation
* **Registration Link:** A direct link to the registration form or platform.
* **Team Size:** The maximum or minimum number of participants per team.
* **Registration Deadline:** The final date for participants to register.
* **Participation Fee:** Any fees associated with participation.

### Prizes and Perks
* **Prize Pool:** The total value of prizes or rewards offered.
* **Prize Categories:** Specific categories for prizes, such as best overall project, most innovative idea, best technical implementation, etc.
* **Perks:** Any additional benefits for participants, such as mentorship, workshops, or access to specific tools or resources.

### Rules and Guidelines
* **Code of Conduct:** A clear outline of expected behavior and ethical guidelines.
* **Judging Criteria:** The criteria that will be used to evaluate projects.
* **Project Submission Guidelines:** Specific instructions for submitting projects, including format, file types, and deadlines.

### Additional Information
* **Organizers:** The names and contact information of the organizers.
* **Sponsors:** The names and logos of any sponsors or partners.
* **FAQs:** A section to address common questions.
* **Social Media Handles:** Links to relevant social media accounts for updates and announcements.
* **Contact Information:** An email address or contact form for inquiries.

**Visual Elements**
* **Banner Image:** A visually appealing banner image to attract attention.
* **Logo:** The official logo of your GDSC or the hackathon.
* **Social Media Sharing Buttons:** Encourage participants to share the event on social media.

**Comment by rishicds** [comment]
Assigned

**Comment by inkerton** [comment]
Hey would you like a simple form or can I be creative in my own way?

**Comment by rishicds** [comment]
@inkerton anything you want
