### ISSUE TITLE
Implementation of a Single Page that will show the extended content for each Hackathons | External Links in Hackathons Page | (Modular Page)

### ISSUE THREAD

**Issue by Shariq2003** [GDSC-RCCIIT/gdg-website#169]
The Hackathons page is currently the static page, that contains Hackathons (Hard Coded in the main hackathon file) and also are linked to external links.
1. I want to Create a Single Page that will show the extended content of each Hackathon.
2. I will use modular programming, by which we can also add more resources in the future by changing just a single file, containing Hackathon in the JSON format ( or can also fetch from backed if added in the future).
3. Which also removed the external dependency

![image](https://github.com/user-attachments/assets/f9b2e1ae-2d9c-48ce-9564-d2e30292dd8b)

**Comment by rishicds** [comment]
I think @inkerton is working on something similar, if she isn't let me know I'll assign this

**Comment by Shariq2003** [comment]
@rishicds no, he is working on the issue of adding hackathon for admin panels
And I am adding the extended page

**Comment by inkerton** [comment]
I already made this page
