### ISSUE TITLE
Single Page that will show the extended content for each Opportunity (Modular Page) | External Links in Careers Page | Extended Opportunity 

### ISSUE THREAD

**Issue by Shariq2003** [GDSC-RCCIIT/gdg-website#170]
The Careers page is currently the static page, that contains Opportunities (Hard Coded in the main resources file) and also are linked to external links that redirect to the other websites.

1. I want to Create a Single Page that will show the extended content of each Opportunity.
2. I will use modular programming, by which we can also add more resources in the future by changing just a single file, containing resources in the JSON format ( or can also fetch from backed if added in the future).
3. Which also removed the external dependency.

![image](https://github.com/user-attachments/assets/b4c08845-c3e3-475b-a93d-8c5928369dd9)

**Comment by rishicds** [comment]
Assigned
