### ISSUE TITLE
Missing Skeleton Loading on All Pages Excepts Home Page | Addition of Skeleton Loading on All pages

### ISSUE THREAD

**Issue by Shariq2003** [GDSC-RCCIIT/gdg-website#171]
![image](https://github.com/user-attachments/assets/ea1c4591-4f79-42c3-8ffc-785fe65f8ff5)

As the Skeleton Loading is just added to the Main page, not at all the pages, I want to add that on all the pages.

**Comment by rishicds** [comment]
Assigned,Don't add it to pages which don't/won't have any dynamic content
