### ISSUE TITLE
3rd Party Links in Footer | Missing Validation in Newsletter | No Submit Button in Footer | No Newsletter Service Attached | React Toast Alerts Missing | Useless Redirection of Footer Links | Linking to Correct Pages of the Website

### ISSUE THREAD

**Issue by Shariq2003** [GDSC-RCCIIT/gdg-website#172]
1. Currently, the Footer is redirecting to 3rd party websites on clicking any link in the footer (even of pages links).
That should be link to the correct pages of the website.

2. Missing Validation in Footer's Newsletter.
3. No submit button in Newsletter.
4. No React Toast Popups.
5. No Newsletter Serviece Attached.

![image](https://github.com/user-attachments/assets/9e28099e-6aae-43cb-93dc-5830435e2237)

https://github.com/user-attachments/assets/7301c093-9971-4716-b1ab-6ad4025dba95

**Comment by rishicds** [comment]
Assigned
