### ISSUE TITLE
Navbar Redesign

### ISSUE THREAD

**Issue by dev129** [GDSC-RCCIIT/gdg-website#174]
Hi @rishicds 
I would like to redesign the Navbar and make it responsive, and add language features into it. Please assign me this issue so that I can start working on it, as soon as possible.

**Comment by rishicds** [comment]
Assigned

**Comment by dev129** [comment]
Hi @rishicds 
This is the final design for navbar , shall I launch PR for it ?

**Comment by dev129** [comment]
![image](https://github.com/user-attachments/assets/9270e416-c720-4140-a911-572ab09a88e3)

**Comment by dev129** [comment]
Hi @rishicds , this is the current design. Any further more modifications ?

**Comment by rishicds** [comment]
Yeah this is good you can give a pr
