### ISSUE TITLE
ADD How to apply page && who can apply page to the website

### ISSUE THREAD

**Issue by shubhagarwal1** [GDSC-RCCIIT/gdg-website#175]

**Comment by rishicds** [comment]
Assigned

**Comment by inkerton** [comment]
@rishicds #144 #142 Already Done 
@shubhagarwal1

**Comment by shubhagarwal1** [comment]
> @rishicds #144 #142 Already Done @shubhagarwal1 Don't waste time on things already done I just saw the issue and thought maybe You both Forgot to check closed PRs so.

Hey @inkerton Thankyou so much for bringing this to my attention, will make it more organised then

**Comment by shubhagarwal1** [comment]
> > @rishicds #144 #142 Already Done @shubhagarwal1 Don't waste time on things already done I just saw the issue and thought maybe You both Forgot to check closed PRs so.
> 
> Hey @inkerton Thankyou so much for bringing this to my attention, will make it more organised then, i will work on how to apply and who can apply page.
