### ISSUE TITLE
ADD a page for Google Developer Experts

### ISSUE THREAD

**Issue by shubhagarwal1** [GDSC-RCCIIT/gdg-website#178]
ref: https://developers.google.com/community/experts
<img width="1372" alt="Screenshot 2024-10-26 at 11 10 49 AM" src="https://github.com/user-attachments/assets/5fcd9b01-6780-44ca-9f77-50a05ef96356">

**Comment by rishicds** [comment]
Hi please finish the 3 issues I've assigned then I can add more
