### ISSUE TITLE
ADD a page for GDG Event Participation Terms

### ISSUE THREAD

**Issue by shubhagarwal1** [GDSC-RCCIIT/gdg-website#179]
ref: https://gdg.community.dev/participation-terms/
<img width="1440" alt="Screenshot 2024-10-26 at 11 12 21 AM" src="https://github.com/user-attachments/assets/3730e8d8-7b1f-48b6-98e6-6c74edee0a2f">

**Comment by inkerton** [comment]
Already added in the hackathon/events page
