### ISSUE TITLE
add contributing.md file

### ISSUE THREAD

**Issue by Amulya-B28** [GDSC-RCCIIT/gdg-website#18]
I would like to add this file because it is a crucial document in open-source repositories, providing clear guidelines and instructions for anyone interested in contributing to the project. It outlines how contributors can get involved, the contribution process, and the repository's coding standards and rules. Please assign this task to me.

**Comment by rishicds** [comment]
hello, this issue is already assigned to someone else, please wait 2 days if they dont give pr Ill assign to you
