### ISSUE TITLE
Google's Free Certifications Page | To Upsikill By Google's Free Certifications & Courses | UI for Issue #188

### ISSUE THREAD

**Issue by Shariq2003** [GDSC-RCCIIT/gdg-website#189]
I want to add a new dedicated webpage that provides a curated list of free certifications and courses offered by Google. This page will serve as a resource for users interested in enhancing their skills through Google’s offerings.

- Page Layout: Follow the existing website theme and layout, ensuring a consistent design.

- List of Courses & Certifications: Display a comprehensive list of Google’s free certifications and courses. Each entry should include:

- Course/Certification Name
- Brief Description
- Direct Link to the course/certification
- Course Duration (if available)
- Certification Availability (if applicable)
- Filters & Search: Add basic filtering options (e.g., by category, duration, difficulty level) and a search bar to improve usability.

- Responsive Design: Ensure the page is fully responsive on all devices, including desktop, tablet, and mobile.

Ref #188 

![image](https://github.com/user-attachments/assets/4df07bbb-d5ab-4972-ba00-7fedefca2fca)

**Comment by rishicds** [comment]
Hi please merge the 3 issues then I'll assign

**Comment by Shariq2003** [comment]
> Hi please merge the previous 3 issues you're assigned then I'll be able to assign these

okay sir

**Comment by Shariq2003** [comment]
> Hi please merge the previous 3 issues you're assigned then I'll be able to assign these

I have raised PRs, please assign now

**Comment by rishicds** [comment]
assigned! And Ive merged your prs
