### ISSUE TITLE
Inetegrate Supabase for User Login 

### ISSUE THREAD

**Issue by shubhagarwal1** [GDSC-RCCIIT/gdg-website#194]
<img width="1440" alt="Screenshot 2024-10-26 at 9 16 44 PM" src="https://github.com/user-attachments/assets/7effb4a1-31fd-42e5-bc7b-18a7f009e1e7">
ref: https://supabase.com/dashboard/projects

**Comment by Aditya-PS-05** [comment]
Can you assign me this issue?
