### ISSUE TITLE
Update the hakathon projects json to adapt to JSON server | Fetch and Update Hackathon Details Page

### ISSUE THREAD

**Issue by inkerton** [GDSC-RCCIIT/gdg-website#195]
this pagecurrently holds no data it is just a template I saw the hackathonprojects list that is a .js file If I can change it to .json then You might be able to fetch from the Json file and also add to the json file using a simple json Server if you want of if not add then atleast you will be able to fetch hackathon details also that file currently does not contains prize info, or dates info. I will add that too should I make it an issue and work on it.

**Comment by rishicds** [comment]
Assigned
