### ISSUE TITLE
Create a Project Details Page

### ISSUE THREAD

**Issue by inkerton** [GDSC-RCCIIT/gdg-website#199]
![image](https://github.com/user-attachments/assets/feb5bf49-be03-4e2f-a9a7-984bbe38d1d8)

**Project Details Page**

A well-structured project details page should provide comprehensive information about a specific project. 

**Basic Project Information:**

* **Project Title:** A clear and concise title that accurately reflects the project's purpose.
* **Project Overview:** A brief summary of the project's goals, objectives, and scope.
* **Project Start and End Dates:** The official start and end dates of the project.
* **Project Manager:** The name and contact information of the project manager.
* **Project Team Members:** A list of team members involved in the project, along with their roles and responsibilities.

**Project Goals and Objectives:**

* **Primary Goals:** The overarching goals that the project aims to achieve.
* **Specific Objectives:** The detailed steps or milestones required to reach the primary goals.

**Project Scope:**

* **In-Scope Activities:** A clear definition of the tasks and deliverables that are included in the project.
* **Out-of-Scope Activities:** A clear definition of the tasks and deliverables that are not included in the project.

**Project Timeline:**

* **Gantt Chart:** A visual representation of the project timeline, showing tasks, dependencies, and deadlines.
* **Milestone Schedule:** A list of key milestones and their target completion dates.

**Project Budget:**

* **Total Project Budget:** The overall budget allocated for the project.
* **Budget Breakdown:** A detailed breakdown of the budget, showing how funds are allocated to different tasks and activities.

**Project Risks and Mitigation Strategies:**

* **Identified Risks:** A list of potential risks that could impact the project.
* **Risk Assessment:** An assessment of the likelihood and impact of each identified risk.
* **Mitigation Strategies:** A plan to minimize or eliminate the impact of identified risks.

**Project Status and Progress:**

* **Current Status:** A summary of the project's current status, including completed tasks, ongoing tasks, and upcoming milestones.
* **Progress Reports:** Links to detailed progress reports or updates.
* **Performance Metrics:** Key performance indicators (KPIs) to measure project success.

**Project Documentation:**

* **Project Plan:** A comprehensive document outlining the project's goals, objectives, scope, timeline, budget, and risk management plan.
* **Technical Documentation:** Detailed technical specifications and design documents.
* **User Manuals:** Instructions for end-users of the project's deliverables.

**Additional Considerations:**

* **Project-Specific Information:** Include any additional information relevant to the specific project, such as client requirements, regulatory compliance, or industry standards.
* **Visual Aids:** Use charts, graphs, and diagrams to enhance understanding and engagement.

**Comment by rishicds** [comment]
Assigned
