### ISSUE TITLE
Lack of code_of_conduct file in your project

### ISSUE THREAD

**Issue by rishyym0927** [GDSC-RCCIIT/gdg-website#2]
Hey can you assign this issue and label it under gssoc-ext level 1

**Comment by rishicds** [comment]
@rishyym0927 assigned

**Comment by tarunkumar2005** [comment]
I can see the issue is open for 2 weeks and still not fixed so assign this to me i will work on this issue.

**Comment by rishicds** [comment]
@tarunkumar2005  assigned
