### ISSUE TITLE
ADD Developer products Page to the application 

### ISSUE THREAD

**Issue by shubhagarwal1** [GDSC-RCCIIT/gdg-website#207]
<img width="1440" alt="Screenshot 2024-10-27 at 2 22 43 AM" src="https://github.com/user-attachments/assets/a5814cce-3218-4b1c-8b9a-fbf58c0ffa1c">
ref: https://developers.google.com/products

**Comment by rishicds** [comment]
@Shariq2003 is making tech toolkits and resources, so combine this page with that to make the user experience more streamlined if possible
