### ISSUE TITLE
GDSC Chapters API Addition | Data Fetching and Cleaning | API Implemenattion for All GDSC Chapters List on a Page

### ISSUE THREAD

**Issue by Shariq2003** [GDSC-RCCIIT/gdg-website#212]
I want to create a service that will fetch all the GDSCs by Google across the Globe and make the data clean and ready to serve on page to list them all.

![image](https://github.com/user-attachments/assets/56da6b7b-864f-4e98-8960-7cc20269d0b0)

**Comment by rishicds** [comment]
assigned
