### ISSUE TITLE
Addition of All GDSC Chapters List on a Page

### ISSUE THREAD

**Issue by Shariq2003** [GDSC-RCCIIT/gdg-website#213]
I want to add the GDSC Chapters Page, which will list all the Google (GDSC) chapters.

It also facilitates the List View with multi-category sorting.

Represent in Map.

### Ref

![image](https://github.com/user-attachments/assets/b1b4153c-116c-4827-8325-2834a0a1d930)

https://github.com/user-attachments/assets/c30d620e-4113-4214-9cc7-944d213cba90

**Comment by rishicds** [comment]
assigned
