### ISSUE TITLE
Integrate Fire base authentication

### ISSUE THREAD

**Issue by dev129** [GDSC-RCCIIT/gdg-website#215]
Hi @rishicds 
I'd like to take on the task of designing the sign-in page with Firebase authentication for the GDG RCIIT website. By working on this, I can ensure a seamless integration of authentication while enhancing the overall design to align with the club’s website theme and improve the user experience. Please consider assigning this issue to me.

**Comment by rishicds** [comment]
working fine for me, do one thing delete the node_modules folder and run npm i again.
make sure you run git fetch and git pull to get the latest changes beforehand

**Comment by shubhagarwal1** [comment]
> working fine for me, do one thing delete the node_modules folder and run npm i again. make sure you run git fetch and git pull to get the latest changes beforehand
> 
> let me know if the issue persists

Hey @dev129 lets connect on discord i will help you solve the problem.

**Comment by dev129** [comment]
Hi @shubhagarwal1 
What is your discord id or account name ?

**Comment by shubhagarwal1** [comment]
> Hi @shubhagarwal1 What is your discord id or account name ?

harry_8409 😂

**Comment by dev129** [comment]
@rishicds pet me be assigned this issue

**Comment by shubhagarwal1** [comment]
Hey @dev129 you can work on this task i have no objections, can you please provide a go through how things are gking to work, as by your current description IT is a bit unclear, also please make sure to ask @rishicds if you can work on it, let him assign the task first

**Comment by rishicds** [comment]
hello, the team will make the backend themselves so we arent accepting any backend related issues, sorry for the trouble, but feel free to work on the frontend as much as you want
