### ISSUE TITLE
Revamp the header

### ISSUE THREAD

**Issue by inkerton** [GDSC-RCCIIT/gdg-website#224]
![image](https://github.com/user-attachments/assets/1da5bfb2-191b-4b7f-ad1b-fd40dd96aa50)

I can change it to 

![image](https://github.com/user-attachments/assets/526f4b23-c34c-46d7-bfba-ef70468b7840)

It would look much much better and you will be able to add as much pages as you want in the future also the cureent alignment is not at  all good

**Comment by inkerton** [comment]
![image](https://github.com/user-attachments/assets/f511b3a0-814b-41c4-8a3c-f7ca5ba4b25c)

**Comment by rishicds** [comment]
assigned
