### ISSUE TITLE
Bug: Signup/Sign-in page image is partially showing on small screen 

### ISSUE THREAD

**Issue by Aditya-PS-05** [GDSC-RCCIIT/gdg-website#228]
## Screenshots
![Screenshot from 2024-10-27 15-36-10](https://github.com/user-attachments/assets/d03b373c-eac7-4234-8a90-0786c143d07f)
![Screenshot from 2024-10-27 15-40-37](https://github.com/user-attachments/assets/0a277d7d-717c-40a6-9ef9-f26542f0947d)

**Comment by Aditya-PS-05** [comment]
Please assign me this issue.

**Comment by inkerton** [comment]
@Aditya-PS-05 This is not an issue on small screen you cannot have the screen divided into halves. It was intended to show the image in half so it add a bit of coloring to the page and the user can easily signup or login as the form matters more .
