### ISSUE TITLE
Update the Events Page to adapt to JSON server | Fetch and Update Events Details Page

### ISSUE THREAD

**Issue by Shariq2003** [GDSC-RCCIIT/gdg-website#231]
As the Website now supports the json server for data interchange, therefore I want to implement the following :-

1. Update the Events page to dynamically fetch event data from a JSON server instead of using a static .js file. 
2. This change will enhance data flexibility, allowing the event's content to be updated externally without modifying the codebase.

**Comment by inkerton** [comment]
i already raised this issue

**Comment by Shariq2003** [comment]
> i already raised this issue

Which Issue @inkerton 
Please refer

**Comment by Shariq2003** [comment]
> i already raised this issue

There is no such an issue exist and also no PR. I have checked already.
If exist please refer to here, maybe I am wrong

**Comment by inkerton** [comment]
#225 
Read the comments I said I will do it for projects and events in the same issue I raised the issue already.

**Comment by Shariq2003** [comment]
> #225 Read the comments I said I will do it for projects and events in the same issue I raised the issue already.

![image](https://github.com/user-attachments/assets/2c743a1f-dfb2-4449-a751-a6d13dd19bbb)

You can do, not yet implemented and also not mentioned that you are going to do.... or not raise any issue.
So I am doing that simple.
