### ISSUE TITLE
Update the Resources Page to adapt to JSON server | Fetch and Update Resource Details Page

### ISSUE THREAD

**Issue by Shariq2003** [GDSC-RCCIIT/gdg-website#232]
As the Website now supports the JSON server for data interchange, therefore I want to implement the following:-

1. Update the Resources page to dynamically fetch resources data from a JSON server instead of using a static .js file. 
2. This change will enhance data flexibility, allowing the resource's content to be updated externally without modifying the codebase.

**Comment by inkerton** [comment]
resource page is static it rarely will get change i have not added resources in the data json server @rishicds

**Comment by Shariq2003** [comment]
> resource page is static it rarely will get change i have not added resources in the data json server @rishicds

where you have added @inkerton 
I have checked

**Comment by Shariq2003** [comment]
> resource page is static it rarely will get change i have not added resources in the data json server @rishicds

Yup, But when the JSON Server is already there, then why a static file this events too, let make it move to JSON server for better scalability

**Comment by inkerton** [comment]
> > resource page is static it rarely will get change i have not added resources in the data json server @rishicds
> 
> where you have added @inkerton I have checked

It is a STATIC page (not dynamic) You need not fetch the resources everytime and enhance load. I provided and added links in the page itself each card has a roadmap attached and they won't change .
