### ISSUE TITLE
Implementataion of Automated Sitemap-Based Route Suggestions via Gemini AI Chat Bubble

### ISSUE THREAD

**Issue by Shariq2003** [GDSC-RCCIIT/gdg-website#235]
Add a chat bubble on the website that leverages Gemini AI to assist users by suggesting routes and answering questions based on the website structure. By providing Gemini AI access to the sitemap.xml and robots.txt files, the chat can suggest relevant pages and help users navigate efficiently.

### Tasks
1. Creation of Sitemap.xml file and robots.txt file
2. Configure Sitemap and Robots Access:
    - Provide Gemini AI access to sitemap.xml and robots.txt to understand the website’s page structure and navigation rules.
3. Implement Chat Bubble Interface:
    - Design and implement a chat bubble interface on the website.
    - Chat bubble will be accessible on all pages for easy user assistance.
4. Integrate Sitemap-Based Suggestion Logic:
    - Program Gemini AI to use the sitemap and robots data to generate automated suggestions and responses.
    - Allow Gemini AI to guide users to the correct page based on their queries.

**Comment by rishicds** [comment]
assigned

**Comment by Shariq2003** [comment]
@rishicds I am adding this issue to pending state because to add the robot.txt to the model, I have to compile the build, which is under processing as the website is not complete and in pending state.

So I am closing this for now, but will open this, asap the build will be ready.
