### ISSUE TITLE
ADD HACKTOBERFEST AND GSSOC BANNER ON THE README

### ISSUE THREAD

**Issue by amiya-cyber** [GDSC-RCCIIT/gdg-website#242]
Issue Description
Describe the bug

The README file is missing the Hacktoberfest and GSSoC banners. The issue is to add these banners at the appropriate location to showcase the project's involvement in these events.

To Reproduce

1. Go to the GitHub repository.
2. Navigate to the README.md file.
3. Scroll down to check for banners related to Hacktoberfest and GSSoC.
4. See that the banners are missing.

Expected behavior

The Hacktoberfest and GSSoC banners should appear on the README file, ideally at the top, to indicate that the project is part of these events.

Additional context

The banners can be sourced from the official Hacktoberfest and GSSoC websites. They should align with the current styling of the README file, and possibly, they could be centered for better visibility.

![2024-10-27 (2)](https://github.com/user-attachments/assets/23e5d7cc-370f-4744-b9b9-6428aae44e4c)

please assign this issue with all level 2 or level 3 label

**Comment by harith-hacky03** [comment]
Can you assign me please?

**Comment by sourabhmajoka** [comment]
Hi @rishicds , I have successfully resolved the issue and created [Pull Request #284 ]. Please review it when you get a chance. Thank you!
