### ISSUE TITLE
BUG : No Response From JSON Server in Hackathon Page | Due to Merge of PR #239

### ISSUE THREAD

**Issue by Shariq2003** [GDSC-RCCIIT/gdg-website#248]
The Hackathon Page getting no response of Data from JSON Server.
Last Merge by PR #239

![image](https://github.com/user-attachments/assets/3d16ba84-cf42-4ff0-bd32-f31d7b7fa03c)

![image](https://github.com/user-attachments/assets/8bd3fcf2-685f-4afb-ab78-82371f9991e3)

https://github.com/user-attachments/assets/974e31d6-9935-40aa-ae3f-aa0c896d64f2

**Comment by Shariq2003** [comment]
@rishicds assigned this to me asap,

**Comment by inkerton** [comment]
if you are running it on codespace or anywhere else It wont start. You need to run it on local this is not a bug also have you even started the server which command did you use and which port ?

**Comment by inkerton** [comment]
also send the ss error its must me a network error if you are not funning it correctly.

**Comment by Shariq2003** [comment]
> also send the ss error its must me a network error if you are not funning it correctly.

whats your problem.
Have you read the description, I have already attached the ss, If you have problems with me, we can connect to solve at once, its enough.
and I am on local, if you want the live video lets connect on meet

**Comment by Shariq2003** [comment]
@MastanSayyad sir, please interfare in this matter, i am tolerating this behavior to much and noticing this whenever I raise any issue on this repo, inkerton have problems

**Comment by inkerton** [comment]
json server mei ek json file aur 3 installments and 1 command to run the server, error ka scope hi nhi h. Jo chiz possible nhi uska issue banane ka kya faeda. i simply asked how you ran the server. i was just trying to help.

**Comment by Shariq2003** [comment]
> json server mei ek json file aur 3 installments and 1 command to run the server, error ka scope hi nhi h. Jo chiz possible nhi uska issue banane ka kya faeda. i simply asked how you ran the server. i was just trying to help.

Okay, if you are trying to help then please make your response polite so that the person in front of you not take your response in negative manner.

Just like you reply,......if you are not running
Why I can make fun by raising issues.

**Comment by Shariq2003** [comment]
You have to mention the steps in your PR.
You have raised an issue for steps, if you mentioned before in the PR, then this issue doesn't make sense, but you have not, that's why

**Comment by Shariq2003** [comment]
Write the proper steps in your PR or here for now.
