### ISSUE TITLE
Landing Page Addition For this Website

### ISSUE THREAD

**Issue by Shariq2003** [GDSC-RCCIIT/gdg-website#25]
There is no landing page at all for the website 

![image](https://github.com/user-attachments/assets/bd22b8ca-d265-4805-ba69-d57837b255fd)

I want to add an attractive and well structured landing page.

@rishicds please assign this to me.

**Comment by rishicds** [comment]
hi, this page is already being worked on, if there is no response from current contributor within one day it will be assigned to @inkerton , who has already made a landing page, after which I can assign it to you, if you wish to make changes

**Comment by Shariq2003** [comment]
> hi, this page is already being worked on, if there is no response from current contributor within one day it will be assigned to @inkerton , who has already made a landing page, after which I can assign it to you, if you wish to make changes

sure sir

**Comment by Shariq2003** [comment]
> hi, this page is already being worked on, if there is no response from current contributor within one day it will be assigned to @inkerton , who has already made a landing page, after which I can assign it to you, if you wish to make changes

@rishicds please assign this to me, as there is no response from him and 2 days passed away more
