### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by inkerton** [GDSC-RCCIIT/gdg-website#250]
Update readme.md so users can run the project as there seems to be some difficulty for those who don't know the proper steps .

like the issue #248 

@rishicds Assign it to me please I will add step by step instructions since I made this it would be best I update the documentation right away so others don't face the same issue.

**Comment by rishicds** [comment]
please close the other issues so i can assign this

**Comment by inkerton** [comment]
Closed the issue made the PR for 3 others.
