### ISSUE TITLE
Addition of Navbar for the Website

### ISSUE THREAD

**Issue by Shariq2003** [GDSC-RCCIIT/gdg-website#26]
I want to add the Navbar in the website which will facilitate the routing from one page to other.

![image](https://github.com/user-attachments/assets/06bb844a-199b-495b-a8f5-af2e8b2b080b)

@rishicds please assign this to me.

**Comment by Shariq2003** [comment]
@rishicds also assign this to me.

**Comment by rishicds** [comment]
this will be added by inkerton first, you can work on top of her navbar

**Comment by rishicds** [comment]
if you wish to work on top of current navbar let me know else I will close this issue @Shariq2003
