### ISSUE TITLE
Creation of Events Page | Showing Events of GDG on Campus RCCIIT

### ISSUE THREAD

**Issue by Shariq2003** [GDSC-RCCIIT/gdg-website#27]
@rishicds please assign this to me.

**Comment by rishicds** [comment]
assigned @Shariq2003

**Comment by Shariq2003** [comment]
Thanks for assigning, will try my best to deliver asap

**Comment by Shariq2003** [comment]
@rishicds please review my PR and also assign Issue #25 and #26 to me
