### ISSUE TITLE
ADD Frameworks, IDEs and SDKs Page to the Application [Products]

### ISSUE THREAD

**Issue by shubhagarwal1** [GDSC-RCCIIT/gdg-website#270]
ref: https://developers.google.com/products/frameworks-ides-and-sdks?category=devsitemarketingidesframeworksandsdks
<img width="1440" alt="Screenshot 2024-10-28 at 3 28 56 AM" src="https://github.com/user-attachments/assets/df10bdca-282e-4f34-b8fe-0716fa3e9760">

**Comment by yashksaini-coder** [comment]
@shubhagarwal1 can I work on this issue
