### ISSUE TITLE
Add careers Page | Add student resources | Any other suggestions

### ISSUE THREAD

**Issue by inkerton** [GDSC-RCCIIT/gdg-website#292]
Create a page with different section to add all these .

I wouldlike to work on it . Please assign me the issue .

**Comment by Shariq2003** [comment]
![image](https://github.com/user-attachments/assets/3e629a1f-4d1a-4d7b-8ef3-8080281b9a0f)

Already there

**Comment by inkerton** [comment]
Not careers page a form page to add career so the admin Panel doenot need to go change the code every time

**Comment by Shariq2003** [comment]
> Not careers page a form page to add career so the admin Panel doenot need to go change the code every time

okay good one,
agreed

**Comment by rishicds** [comment]
assigned, yes add a career form with some mcq type questions that can suggest a career also if possible, would make it more unique, you can also use gemini to suggest a career path based on questions answers

**Comment by inkerton** [comment]
Ok sure I will look into it

**Comment by inkerton** [comment]
is this gemini chat working
![image](https://github.com/user-attachments/assets/0e01359f-896d-45da-bfb2-378eb8158b5f)


In my code I fetched the latest one I don't see any api/generate-content

@rishicds is this still pending or not done correctly ??? I could use it if it is completed?

**Comment by Shariq2003** [comment]
Have you added your api

**Comment by Shariq2003** [comment]
Hey I have found that someone deleted the api folder inside the pages folder that contained the Gemini route

**Comment by Shariq2003** [comment]
Let me check this.

**Comment by Shariq2003** [comment]
@rishicds someone deleted the folder of api inside pages folder that contained the routes of Google certificatuon and Gemini ai route, let me fix this first, I am raising a PR to fix that and also please do not add any label to that PR

**Comment by Shariq2003** [comment]
> @Shariq2003 let me know once you fix it

Sure, 
Do you want to work on the UI or something else on that pages.

**Comment by inkerton** [comment]
i want to make a form page with some mcq type questions that can suggest a career also if possible, would make it more unique, you can also use gemini to suggest a career path based on questions answers

**Comment by Shariq2003** [comment]
can we connect over discord

**Comment by Shariq2003** [comment]
![image](https://github.com/user-attachments/assets/ac075374-7bfe-4ae3-8c27-6120abf25fda)

@inkerton everything is fine and working
