### ISSUE TITLE
Add Header and Footer

### ISSUE THREAD

**Issue by akdwivedi-explorer** [GDSC-RCCIIT/gdg-website#3]
Add header section which contains 
* Home
* About us
* Gallery
* Team
* Contact us
* Events

Also this will contain logo of the gdg rcciit

Please assign this to me under Hacktoberfest. I will made this more attractive and responsive. I have a good understanding of Next.js, React.js and Tailwind CSS, Shadcn/ui, etc. Currently I am also working on my college website and made the GDSC website of my college.

**Comment by rishicds** [comment]
@akdwivedi-explorer  assigned

**Comment by akdwivedi-explorer** [comment]
Could you please share me the navbar details and footer details so that I
will easily make the components?
May I know your requirement?
If you have any design or anything that you want that your website should
look like, you can share it with me!
Please share the colour pallets so that website should look according to
your requirement.

**Comment by rishicds** [comment]
You can make it similar to this, https://www.adfolio.design/landing-pages/6hydjnn3pruiz2z?from=lp-archive
Color pallete can be a nice pastel color.

In the header will the things you mentioned, in footer you can place some random placeholder links for now

**Comment by akdwivedi-explorer** [comment]
Awesome, thanks!

**Comment by akdwivedi-explorer** [comment]
It will be done by today itself.

**Comment by rishicds** [comment]
if you havent finised I will assign the issue to someone else @akdwivedi-explorer

**Comment by akdwivedi-explorer** [comment]
I have finished it.

**Comment by akdwivedi-explorer** [comment]
I will raise the PR soon.
