### ISSUE TITLE
bug: The navbar is not closing after clicking

### ISSUE THREAD

**Issue by AE-Hertz** [GDSC-RCCIIT/gdg-website#305]
bug: The navbar is not closing after clicking any labels in dropdown

Demostration:

https://github.com/user-attachments/assets/5032882b-adcd-40ea-81d4-0ad7cb0e8b5f

see the dropdown is not closing after clicking hackathon button , the dropdown should close.
I will fix this issue.

assign me this issue under gssoc-ext and hacktoberfest.

**Comment by rishicds** [comment]
assigned
