### ISSUE TITLE
Creating a custom 404 page 

### ISSUE THREAD

**Issue by dev129** [GDSC-RCCIIT/gdg-website#31]
#### Description
The current 404 error page does not provide an optimal user experience, especially in a production environment. A well-designed custom 404 page can enhance the overall aesthetic and usability of the site.

#### Proposed Solution
I propose to design a custom 404 error page that aligns with the site's branding and improves user engagement. 

#### Plan
1. **Labeling**: Please assign the issue the `GSSOC-ext` and `Hacktoberfest` and `level` labels.
2. **Wireframe**: I will share a wireframe within the first hour of being assigned to the issue.
3. **Approval**: Upon receiving approval for the wireframe, I will start the design process.
4. **Completion**: The design will be completed within 24 hours of wireframe approval.

#### Benefits
- Improved user experience and site navigation.
- Enhanced branding consistency.
- Potential reduction in bounce rates.

I look forward to your feedback and hope to contribute positively to the project!

**Comment by rishicds** [comment]
assigned @dev129

**Comment by dev129** [comment]
![image](https://github.com/user-attachments/assets/0d989e66-2422-491c-addd-5fbf633c205b)
Please also assign the hacktober label and let me know if the above design is suitable and then shall i start designing it.

**Comment by dev129** [comment]
Are you there @rishicds ?

**Comment by dev129** [comment]
@rishicds, atleast tell me if I should design or not ?

**Comment by rishicds** [comment]
Hi, sorry I didn't get notified,yes you can continue with this

**Comment by dev129** [comment]
https://github.com/user-attachments/assets/3f525ebd-efd1-4112-89b6-03ce7659cd05

Here I have not used the logo of GDSC-RCIIT yet, but will do in the final cut also it is reposive, let me know as soono as possible @rishicds

**Comment by rishicds** [comment]
Very nice! @dev129

**Comment by rishicds** [comment]
It's okay, give pr, I'll merge it in a bit @dev129

**Comment by dev129** [comment]
Done @rishicds, check it and let me know.

**Comment by rishicds** [comment]
done @dev129

**Comment by dev129** [comment]
done @rishicds
