### ISSUE TITLE
I want to add the PULL REQUEST TEMPLATE 

### ISSUE THREAD

**Issue by souvikpramanikgit** [GDSC-RCCIIT/gdg-website#315]
I want to add the PULL REQUEST TEMPLATE like this as i see in this repository you don't have any template when you are creating a pull request that;s reason i want to add this template->

![image](https://github.com/user-attachments/assets/9c6e953f-1e31-4557-ab37-9f70f67f6801)

**Comment by rishicds** [comment]
assigned
