### ISSUE TITLE
🧑‍💻: Make the spotlight jobs section responsive | fetch the job details and display them in an interactive Page

### ISSUE THREAD

**Issue by inkerton** [GDSC-RCCIIT/gdg-website#329]
### Title

🧑‍💻: Make the spotlight jobs section responsive | fetch the job details and display them in an interactive Page

### Enhancement Aim

1. The spotlight jobs section is not responsive that needs to be made responsive 
2. Changing the job details I currently added the same jobs as before in the JSON server but I a don't think a GSDC Community is supposed to have jobs like that
3. data in the json server needs to be changed
4. Job Description Page

### Changes

I don't think a GDSC community is supposed to have jobs like these 
"
Consumer Hardware
Job Description
Create devices that enhance people's lives.
Develop consumer hardware that integrates seamlessly with software products.
Your work will directly influence the usability and functionality of our devices.
Building products that improve daily life.

Minimum Qualifications
Bachelor's degree in Electrical Engineering or related field.
4+ years of experience in hardware design and development.
Knowledge of digital and analog circuit design.
"

### Screenshots 📷

![image](https://github.com/user-attachments/assets/d82d930e-3bf8-4e60-aef3-f51a0a0d3524)
![image](https://github.com/user-attachments/assets/c2b47b3d-431e-4381-a587-13d9c3529a08)

### Full Name

inkerton

### Participant Role

GSSOC

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

**Comment by rishicds** [comment]
someone is already working on this
