### ISSUE TITLE
Enhance and Structure the Contributor Section

### ISSUE THREAD

**Issue by alo7lika** [GDSC-RCCIIT/gdg-website#337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

- Updated contributor graph to use the Vaunt API for dynamic contributor visuals.
- Structured the contributor section for better presentation.
- Added responsive alignment for the contributor images.

### Suggested Change

- Reformat Contributor Section: Use a grid layout to make the section visually appealing and organized.
- Add Images: Display contributor GitHub avatars with a consistent size.
- Include Links: Add links to each contributor's GitHub profile directly.
- Use Badges: Include badges that showcase contributions such as "Maintainer," "Top Contributor," or specific GitHub activity (stars, forks).
- Group Contributors: Categorize contributors based on the type of contribution (e.g., code, documentation, design).
- Include Automation: Consider using GitHub tools like all-contributors to automate the addition and maintenance of contributors.

### Rationale

N/A

### Urgency

High

### Acknowledgements

- [X] I'm a GSSOC'24-Extd contributor
- [X] I'm a Hacktoberfest contributor
- [X] I am willing to work on this issue (optional)

![Screenshot 2024-10-25 212547](https://github.com/user-attachments/assets/37f869a3-dc89-4dfb-92ce-b49fc5d3fafd)

**Comment by alo7lika** [comment]
@rishicds kindly assign me the task

**Comment by rishicds** [comment]
merge this and #343 into a single issue and close these two
