### ISSUE TITLE
Addition of Frontend Development Roadmap 

### ISSUE THREAD

**Issue by pratheekv39** [GDSC-RCCIIT/gdg-website#340]
@rishicds I have already completed 3 roadmaps , i.e., C++ , DSA and  Competitive Programming Learning Track (Please review my sent PR for Competitive track) ... 
I would love to work on this section as well. Kindly assign me this issue and I will start working on it immediately once you approve the PR. Thanks :)

**Comment by rishicds** [comment]
assigned but follow the instructions I have given in your recent PR

**Comment by pratheekv39** [comment]
@rishicds Sure 👍🏼
