### ISSUE TITLE
Enhance Sign Up Component with Improved UI and Functionality

### ISSUE THREAD

**Issue by dfordebarati** [GDSC-RCCIIT/gdg-website#344]
### Title

Enhance Sign Up Component with Improved UI and Functionality.

### Enhancement Aim

The aim of this enhancement is to improve the user interface (UI) of the Sign Up component, making it more user-friendly and visually appealing. Additionally, I have implemented better validation mechanisms for the input fields to enhance user experience and prevent errors.

### Changes

1. **UI Improvements:**
- Updated styling for input fields, buttons, and overall layout for a cleaner look.
- Added visual feedback for password strength and validation errors.
- Enhanced the layout to make it more responsive and accessible.

3. **Functionality Enhancements:**
- Implemented password strength validation to provide real-time feedback to users.
- Improved error handling to inform users of required fields and incorrect input formats.
- Added functionality to remember user preferences regarding marketing updates.

### Screenshots 📷

N/A

### Full Name

Debarati Seal

### Participant Role

GSSOC Contributor

### Guidelines

- [X] I have read the guidelines
- [ ] I have the link to my latest merged PR

**Comment by rishicds** [comment]
merge #345 and #344 into a single issue
