### ISSUE TITLE
🧑‍💻: 'Join Us' Button Not Functional in Home Page Hero Section

### ISSUE THREAD

**Issue by Priyanshi0112** [GDSC-RCCIIT/gdg-website#351]
### Title

'Join Us' Button Not Functional in Home Page Hero Section

### Enhancement Aim

The 'Join Us' button in the hero section of the home page is currently unresponsive. Clicking the button does not trigger any action, which can lead to confusion for users looking to join. This issue should be addressed by linking the button to the appropriate sign-up or registration page, ensuring that users can easily navigate to join the platform. This fix will enhance user flow and engagement on the site.

### Changes

NA

### Screenshots 📷

https://github.com/user-attachments/assets/3ed724b1-01d4-4c39-af9f-e56ad599dcd5

### Full Name

Priyanshi Bhargava

### Participant Role

GSSOC - Extd

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

**Comment by rishicds** [comment]
assigned
