### ISSUE TITLE
🧑‍💻: redesign the navbar

### ISSUE THREAD

**Issue by priyashuu** [GDSC-RCCIIT/gdg-website#352]
### Title

i want to redesign te navbar 

### Enhancement Aim

it will increase the interactive for the users

### Changes

https://github.com/user-attachments/assets/fe4f504b-ee0c-4a8b-9dfb-2fe298c1fdaa

### Full Name

Priya Rani

### Participant Role

Gssoc, hackoctoberfest

### Guidelines

- [X] I have read the guidelines
- [ ] I have the link to my latest merged PR

**Comment by rishicds** [comment]
not accepting navbar redesigns as of now
