### ISSUE TITLE
🧑‍💻: Correct the data added in json | A page to read the whole story | add all the fields in achievements and stories 

### ISSUE THREAD

**Issue by inkerton** [GDSC-RCCIIT/gdg-website#354]
### Title

🧑‍💻: Correct the data added in json | A page to read the whole story | add all the fields in achievements and stories 

### Enhancement Aim

 these stories and achievements under the spotlight jobs do not have any id neither do they have any info. Also the mentors have no id  Atleast tell them to follow the structure of the json . The job , project testimonial info is not present in the json . If these deatils are being added then they need to add all the details not just names or one liners. Their is a Read more Button but it does not lead anywhere.
The achievements and mentors addition were causing the conflict. I worked out a solution for the backend for now but json servers also have a protocol that needs to be followed.

![image](https://github.com/user-attachments/assets/08251bf0-33f0-4bd3-bbc8-5241f4c67ff1)

### Changes

Stories need more inflo like time duration they worked for Project details proper like name , languages used, Your role, etc

Mentors too have no github , linkedin link no info about their past career .

### Full Name

inkerton

### Participant Role

GSSOC

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

**Comment by inkerton** [comment]
@rishicds also You assigned me an issue #237 and then I saw a PR #349 Please don't assign the same issue to two people Now what he has added and what I have added are completely different. No id no way to fetch a particular job also what he added are not jobs are events they shuld be under events in careers their should be roles for joining  gdsc community. Like frontend, backend, marketing, community manager, etc. Workshop details under Careers Is not right. I am guessing You didn't recheck the info added or the issue which you assigned twice to two people. 

"title": "AI for Social Good Hackathon", "title": "Blockchain & Cryptocurrency Workshop","title": "Women in Tech Leadership Conference", "title": "Data Science Bootcamp",


It would be a humble request not to assign the same issue twice. I really scorched the whole internet to find a simple solution to replace MongoDB or any database so this project could still have a backend. If any person wants to add any data in the JSON, please tell them to ask me. I would gladly help or tell them to add appropriate data.

**Comment by rishicds** [comment]
my bad, ill assign issues more carefully from next time
