### ISSUE TITLE
🧑‍💻: Make a new Page to display Stories and achievements like a blog

### ISSUE THREAD

**Issue by inkerton** [GDSC-RCCIIT/gdg-website#355]
### Title

🧑‍💻: Make a new Page to display Stories and achievements like a blog

### Enhancement Aim

To make a new page where the achievement and story is fetched from the json based on id. 
and display them in a new blog post page so students can be attracted to it . As said in #354 

### Changes

To make a new page where the achievement and story is fetched from the json based on id. 
and display them in a new blog post page so students can be attracted to it . As said in #354 

### Full Name

inkerton

### Participant Role

GSSOC 

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

**Comment by rishicds** [comment]
assigned
