### ISSUE TITLE
🧑‍💻: Enhancement of the Sign-In and Sign-Up Components with Improved UI and Functionality

### ISSUE THREAD

**Issue by dfordebarati** [GDSC-RCCIIT/gdg-website#356]
### Title

🧑‍💻: Enhancement of the Sign-In and Sign-Up Components with Improved UI and Functionality

### Enhancement Aim

This enhancement aims to improve the user experience and functionality of both the SignIn and SignUp components by implementing several key features that enhance usability, accessibility, and visual appeal. The changes proposed focus on better validation, user feedback, and improved UI elements to align with modern design standards and improve overall user interaction.

### Changes

**Changes to SignIn Component:**

- Email Validation: Real-time email format validation to ensure a correct email address is entered, with an error message displayed for invalid formats.
- Loading Indicators: A loading state to provide visual feedback during sign-in attempts, enhancing user engagement.
- Remember Me Functionality: "Remember Me" checkbox that saves the user’s email in local storage, allowing a more convenient login experience in the future.
- Password Visibility Toggle: A toggle button for users to show or hide their password, making it easier to verify the password entry.
- Reset Button: A Reset button to clear input fields, enabling users to quickly start over if needed.
- UI Enhancements: Improved styling and layout for a cohesive, visually appealing design that aligns with modern UI standards.

**Changes to SignUp Component:**

1. UI Improvements: 

- Updated styling for input fields, buttons, and layout to create a cleaner, more polished appearance.
- Visual feedback for password strength and validation errors, making it easier for users to meet password requirements.
- Responsive and accessible layout enhancements for a smoother experience across different devices.

2. Enhanced Functionality:

- Real-time password strength validation to guide users in choosing secure passwords.
- Improved error handling to notify users about required fields and incorrect input formats.
- Added functionality to remember user preferences regarding marketing updates, improving customization and user satisfaction.

### Screenshots 📷

![image](https://github.com/user-attachments/assets/652c263d-aedc-4092-bbbd-3b92475143db)
![image](https://github.com/user-attachments/assets/940b61ef-1657-4259-86f4-423297b02290)

### Full Name

Debarati Seal

### Participant Role

GSSoC 24 Extd Contributor

### Guidelines

- [X] I have read the guidelines
- [ ] I have the link to my latest merged PR

**Comment by rishicds** [comment]
assigned
