### ISSUE TITLE
User Interface Enhancements | Addition Of FAQS And User Forum Page 

### ISSUE THREAD

**Issue by Shariq2003** [GDSC-RCCIIT/gdg-website#36]
I also want to add a FAQS Page and User Forum Page for this website.

**Comment by rishicds** [comment]
assigned

**Comment by rishicds** [comment]
please make the design similar to inkertons as in #37 #38 #39

**Comment by Shariq2003** [comment]
> please make the design similar to inkertons as in #37 #38 #39

Okay sir
