### ISSUE TITLE
[BUG] contact us button is not working on home page 

### ISSUE THREAD

**Issue by Priyanshi0112** [GDSC-RCCIIT/gdg-website#360]
### Description

The "Contact Us" button on the home page is not functional. Clicking the button does not trigger any response or redirect to the contact section/page as expected.

### Screenshots

https://github.com/user-attachments/assets/7039d0ae-cc19-4269-b543-0c05ef4dff5d

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/alo7lika/gdg-website/blob/DEV/contributing.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by rishicds** [comment]
assigned
