### ISSUE TITLE
🧑‍💻: Add Testimonials page

### ISSUE THREAD

**Issue by Subashree-selvaraj** [GDSC-RCCIIT/gdg-website#362]
### Description

Collect and showcase testimonials from community members about their experiences, growth, and the impact of GDG in their professional and personal lives. This page will highlight positive feedback and stories to inspire and attract new members to the community.

### Full Name

Subashree S

### Participant Role

gssoc'24 ext

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

**Comment by rishicds** [comment]
Hi,thank you for taking your time to create this issue but currently we don't have any plans for a testimonial page
