### ISSUE TITLE
[Doc]: Want to add security

### ISSUE THREAD

**Issue by Dipanita45** [GDSC-RCCIIT/gdg-website#363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Added security

### Suggested Change

Security of the website

### Urgency

Medium

### Acknowledgements

- [X] I'm a GSSOC'24-Extd contributor
- [ ] I'm a Hacktoberfest contributor
- [X] I am willing to work on this issue (optional)

**Comment by rishicds** [comment]
explain the issue properly please

**Comment by Dipanita45** [comment]
I will add necessary security to protect the website against the harms and
no-one can misuse

**Comment by rishicds** [comment]
what kind of security? @Dipanita45

**Comment by Dipanita45** [comment]
Data security, and necessary security and action to the website

**Comment by Dipanita45** [comment]
Please assign me this issue

**Comment by rishicds** [comment]
Assigned but show me what you have made before giving PR
