### ISSUE TITLE
🧑‍💻: Addition of Java Learning Roadmap

### ISSUE THREAD

**Issue by shivenyadavs** [GDSC-RCCIIT/gdg-website#379]
### Title

Addition of Java Learning Roadmap

### Enhancement Aim

Enhancement Aim: The goal of this enhancement is to add a Java Learning Roadmap to guide beginners and intermediate learners through essential Java concepts in a structured, step-by-step manner. This roadmap will provide a clear learning path, helping users build a solid foundation in Java programming.

### Changes

**Learning Modules:** Introduce modules that cover Java basics, object-oriented programming, data structures, algorithms, and advanced topics.
**Visual Roadmap:** Add a visual representation of the roadmap to make navigation intuitive.
**Resource Links:** Provide links to tutorials, code samples, and documentation for each topic.
**Project Ideas:** Include project suggestions at each stage to apply concepts in real-world scenarios.
**Progress Tracker:** Allow users to track their progress through different stages of the roadmap.

### Screenshots 📷

N/A

### Full Name

Shiven yadav s

### Participant Role

GSSOC, Hacktoberfest

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

**Comment by pratheekv39** [comment]
@shivenyadavs Hi , if you get assigned this issue , please use id:7 .....I have implemented all roadmaps till now. Just follow the existing UI Principles that I have used for current  pages to maintain consistency across all pages .

**Comment by rishicds** [comment]
@shivenyadavs check the codebase first will you be able to implement it in the same way other topics are implemented?

**Comment by shivenyadavs** [comment]
> @shivenyadavs Hi , if you get assigned this issue , please use id:7 .....I have implemented all roadmaps till now. Just follow the existing UI Principles that I have used for current pages to maintain consistency across all pages .

i didnt get you

**Comment by pratheekv39** [comment]
@shivenyadavs Nevermind, check the codebase completely and understand it first.Then, ask to get assigned regarding issues....

**Comment by rishicds** [comment]
@shivenyadavs will u be able to do this or I'll assign someone else

**Comment by rishicds** [comment]
@pratheekv39 will u be able to do this?

**Comment by pratheekv39** [comment]
@rishicds Sure , I will work on it

**Comment by rishicds** [comment]
@pratheekv39 assigned
