### ISSUE TITLE
Addition of Cloud Computing & DevOps Roadmap

### ISSUE THREAD

**Issue by pratheekv39** [GDSC-RCCIIT/gdg-website#383]
@rishicds I have completed implementing all the current existing roadmaps. However, I think some roadmaps are not covered . So , I will start with Cloud Computing & DevOps Roadmap. 
i)The same style and UI Principles will be followed
ii)Will add an extensive, comprehensive roadmap for this as well

Kindly , assign this issue to me after reviewing the last sent PR .... Thanks :)

**Comment by rishicds** [comment]
Assigned
