### ISSUE TITLE
🧑‍💻: Loading Animation before Landing Page 

### ISSUE THREAD

**Issue by dev129** [GDSC-RCCIIT/gdg-website#397]
### Issue Title: Add Loading Animation to Landing Page

**Description:**
To enhance the user experience, a loading animation should be added to the landing page. This feature will create a smoother transition as users wait for the content to load, improving the visual appeal and perceived performance.

**Acceptance Criteria:**
- The loading animation appears when the landing page is accessed.
- The animation is displayed for a set duration or until the content is ready.
- Smooth transition from the loading animation to the main content.
- No noticeable performance issues due to the loading animation.
- Works seamlessly on both desktop and mobile devices.

**Additional Notes:**
Feedback from testing and user interaction should be gathered to fine-tune the duration and style of the animation.

### Enhancement Aim

**Aim:**
The goal is to implement a loading animation that displays when the landing page is being loaded and disappears when the content is ready. The animation should last for a brief period, ideally a few seconds, to engage users without causing delays.

### Changes

**Proposed Changes:**
- Develop a visually appealing loading animation that complements the current design.
- Implement conditional rendering logic to show the loading animation before the main content loads.
- Ensure the loading animation does not significantly impact page load performance.
- Verify compatibility across different browsers and screen sizes to maintain responsiveness.

### Full Name

Devansh Vishwa

### Participant Role

gssoc-ext (contributor)

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

**Comment by rishicds** [comment]
Assigned, please show what kind of animation you'll add

**Comment by dev129** [comment]
Hi @rishicds , this is something new i have tried exclusively for your website 
 

https://github.com/user-attachments/assets/db908021-e6c5-4c92-837e-d4df7d3bdf14

There might be some timing delays, rest if you feel any other thing should be added let me know.

**Comment by dev129** [comment]
Hi @rishicds , did you like the design ?

**Comment by rishicds** [comment]
> Hi @rishicds , did you like the design ? 
> 

Hi sorry I forgot to reply to this, it's awesome 💯, you can give pr

**Comment by rishicds** [comment]
@dev129 can you make the text GDGC RCCIIT

**Comment by dev129** [comment]
@rishicds , so you want Google Developers Group as the title and RCCIIT, Kolkata as subtext (below the GDG), because logically RCCIIT is a Campus which people know.

**Comment by rishicds** [comment]
> @rishicds , so you want Google Developers Group as the title and RCCIIT, Kolkata as subtext (below the GDG), because logically RCCIIT is a Campus which people know.

Yeah

**Comment by dev129** [comment]
Hi @rishicds , check this one 
https://github.com/user-attachments/assets/24194bab-2d9d-4255-b8f3-526009e155bc

And tell quickly so I can raise pr

**Comment by rishicds** [comment]
> Hi @rishicds , check this one 
> https://github.com/user-attachments/assets/24194bab-2d9d-4255-b8f3-526009e155bc
> 
> And tell quickly so I can raise pr 

Perfect

**Comment by dev129** [comment]
Hi @rishicds , a ver crucial thing not mentioned ij my pr , include in your documentation , to define the cloudinary attributes mandatorily

**Comment by dev129** [comment]
Else the video wont work and secondly test it the video is working or bot , it is defined in the hero.jsx file , test the path on your local machine also.

**Comment by rishicds** [comment]
> Hi @rishicds , a ver crucial thing not mentioned ij my pr , include in your documentation , to define the cloudinary attributes mandatorily 

Hi your cloudinary variables didn't come,please provide them and I'll add it

**Comment by rishicds** [comment]
@dev129  can you provide the video file in a drive link

**Comment by dev129** [comment]
Ok

**Comment by dev129** [comment]
If I share my env variables, then how will you add / remove files in long run ? If you need help in setting that up let me know.

**Comment by rishicds** [comment]
> If I share my env variables, then how will you add / remove files in long run ? If you need help in setting that up let me know.

You won't need to share your env variables I'll upload the video you made to my own cloudinary account
