### ISSUE TITLE
🧑‍💻: Adding an open source learning track for students

### ISSUE THREAD

**Issue by VinayLodhi1712** [GDSC-RCCIIT/gdg-website#402]
### Title

What more students expect is they guide them in learning resources and nowadays they need how they can become an open source contributor and like which programs they can participate and all.

### Enhancement Aim

Gives students knowledge about the open source 

### Changes

in learning tracks

### Full Name

Vinay Anand Lodhi

### Participant Role

GSSOC

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

**Comment by rishicds** [comment]
Please check the project structure, follow it, assigned
