### ISSUE TITLE
🧑‍💻: DEPLOYMENT LINK

### ISSUE THREAD

**Issue by Meetpidev** [GDSC-RCCIIT/gdg-website#414]
### Title

DEPLOYMENT LINK

### Enhancement Aim

YOU SHOULD DEPLOY THIE WEBSITE IF NOT DEPLOYED.. AND IF ITS ALREADY DEPLOYED THEN YOU SHOULD ADD INTO README.md FILE,,

### Changes

DEPLOY IT AND ADD IN README.md FILE

### Full Name

MEET SHAH

### Participant Role

CONTRIBUTER

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

**Comment by Meetpidev** [comment]
@rishicds can i work on it ?

**Comment by rishicds** [comment]
Not needed, we will do it ourselves
