### ISSUE TITLE
🧑‍💻: Game Development Roadmap

### ISSUE THREAD

**Issue by dev129** [GDSC-RCCIIT/gdg-website#449]
### Title

**Title**: Create a Comprehensive Game Development Roadmap for GDSC RCCIIT Website

Hi @rishicds 

### Issue Description

Game development is a popular area of interest for many students and developers. To help GDSC RCCIIT members get started with game development, it would be highly beneficial to create a **Game Development Roadmap**. This roadmap will guide members through the essential concepts, tools, and techniques needed to create games, starting from the basics and progressing to advanced skills.

### Goals of the Game Development Roadmap

1. **Beginner Level**:
   - Introduction to game development and popular game engines (Unity, Unreal Engine, Godot)
   - Basic programming concepts for game development (C#, C++, Python)
   - Understanding 2D vs. 3D game development
   - Simple project: Building a basic 2D game (e.g., Pong or a simple platformer)

2. **Intermediate Level**:
   - Working with 3D environments and assets
   - Introduction to physics and collision detection in games
   - Animations and character movements
   - Basic AI concepts for games (e.g., enemy movement and decision-making)
   - Simple project: Building a 3D game prototype with basic animations

3. **Advanced Level**:
   - Advanced AI (pathfinding, complex behaviors)
   - Multiplayer game development basics
   - Performance optimization for games
   - Understanding shaders and visual effects
   - Advanced project: Building a full-featured game with multiplayer functionality

### Expected Outcome

1. A **structured guide or README** file within the repository that breaks down each topic with recommended resources, tutorials, and exercises.
2. Links to **external resources** (courses, documentation, video tutorials) for each level.
3. Sample **projects and challenges** for each level to help members practice and apply what they learn.

### Suggested Implementation

1. **Collaborative Development**:
   - Divide the roadmap into distinct sections and allow contributors to focus on areas where they have expertise or interest.
   - Each contributor can work on a section (e.g., 2D basics, 3D modeling, AI) and submit it as a pull request.

2. **Resource Curation**:
   - Curate resources for each level (beginner, intermediate, advanced) from popular and free sources.
   - Include documentation on game engines like Unity, Unreal, and Godot, as well as any software commonly used in game development, such as Blender for 3D modeling.

3. **Progress Tracking**:
   - Use GitHub Projects or Milestones to track the progress of each section, making it easy for contributors to see the roadmap’s overall completion status.

### Full Name

Devansh Vishwa

### Participant Role

gssoc-ext

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

**Comment by dev129** [comment]
Hi @rishicds 

![image](https://github.com/user-attachments/assets/1dc59f2e-611a-436c-8f33-6fd44b40ca56)
![image](https://github.com/user-attachments/assets/964825a0-a7d9-44e3-bab0-a9a5beda4aeb)
![image](https://github.com/user-attachments/assets/245d0a7e-ab57-4ccb-9259-92fae85f57ae)

Video:
https://github.com/user-attachments/assets/dcae55d8-6315-4777-bdff-d06d3b82075c

**Comment by rishicds** [comment]
Nicee good job @dev129 , you can give pr

**Comment by dev129** [comment]
a small question @rishicds , please tell me that in your projects section, what projects are you actually planning to put ?

**Comment by rishicds** [comment]
> a small question @rishicds , please tell me that in your projects section, what projects are you actually planning to put ? 

We plan to host hackathons in our college and plan to put winning projects on there

**Comment by dev129** [comment]
Oh so what about your projects on github , won't you show those projects ?

**Comment by rishicds** [comment]
> Oh so what about your projects on github , won't you show those projects ? 

Nah we won't put our projects on there mp

**Comment by dev129** [comment]
Ohk, and what about your events , haven't you held them earlier also , cuz i see no mention of them.

**Comment by dev129** [comment]
Well I must say the website actually has gone way awesome than you could have thought.

**Comment by rishicds** [comment]
> Well I must say the website actually has gone way awesome than you could have thought. 

Yeah probably one of the best gdg websites we've seen

**Comment by dev129** [comment]
Its a pleasure to work with you as PA, but do check the code before merging , the website landing page is unresponsive in mobile view , check your linkedin
