### ISSUE TITLE
FRONTEND ISSUE: wrong words written on sign up form

### ISSUE THREAD

**Issue by VinayLodhi1712** [GDSC-RCCIIT/gdg-website#457]
### Preliminary Checks

- [X] I have checked the browser console for errors
- [X] I have searched the existing issues

### Issue Summary

![image](https://github.com/user-attachments/assets/447f34bc-3ff7-428f-8b47-07e8287a90e8)
Here Login should be written but instead Sign-up is written
It should be like Already have an account? Login 

### Steps to Reproduce

Go to signup page.

### Additional Information

- [X] I agree to follow this project's Code of Conduct
- [X] I can provide more details if needed

**Comment by rishicds** [comment]
assigned
