### ISSUE TITLE
🧑‍💻:  CLICKABLE CARDS

### ISSUE THREAD

**Issue by Meetpidev** [GDSC-RCCIIT/gdg-website#458]
### Title

CLICKABLE CARDS

### Enhancement Aim

THESE CARDS SHOULD BE CLICKALE SO THAT WE CAN DIRECTLY SEE THAT DETAILS..

### Changes

MAKE IT CLICKALBE

### Screenshots 📷

![image](https://github.com/user-attachments/assets/4d8ca753-47f8-4083-99bf-7ca2f12ece9a)

### Full Name

MEET SHAH

### Participant Role

CONTRIBUTER

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

**Comment by Meetpidev** [comment]
@rishicds Can i work on it ?

**Comment by Meetpidev** [comment]
@rishicds can i work on it ?

**Comment by rishicds** [comment]
Assigned

**Comment by Meetpidev** [comment]
@rishicds please accept PR as soon as possible when i will send PR about it

**Comment by Meetpidev** [comment]
@rishicds Please Review PR..
