### ISSUE TITLE
🧑‍💻:  FOLLOW AND CONTACTUS DETAILS 

### ISSUE THREAD

**Issue by Meetpidev** [GDSC-RCCIIT/gdg-website#459]
### Title

FOLLOW AND CONTACTUS DETAILS ARE SAME

### Enhancement Aim

IN FOOTER THE WE DONT NEED FOLLOW US COLOUM BECAUSE CONTACTUS AND FOLLOWUS DETAILS ARE SAME WE CAN COMINE THEM ALSO..

### Changes

WE CAN COMINE THEM ALSO..

### Screenshots 📷

![image](https://github.com/user-attachments/assets/25e73242-c133-4891-ab7c-6edbca448952)

### Full Name

MEET SHAH

### Participant Role

CONTRIBUTER

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

**Comment by Meetpidev** [comment]
@rishicds Can i work on it ?

**Comment by Meetpidev** [comment]
@rishicds can  work on it ?

**Comment by rishicds** [comment]
instead of follow us link it to various pages of the site

**Comment by Meetpidev** [comment]
@rishicds Please Review PR..
