### ISSUE TITLE
🧑‍💻:  GIT AND GITHUB LEARNING TRACK

### ISSUE THREAD

**Issue by Meetpidev** [GDSC-RCCIIT/gdg-website#460]
### Title

GIT AND GITHUB LEARNING TRACK

### Enhancement Aim

WE SHOULD ALSO INCLUDE GIT AND GITHUB LEARNING TRACK SO THAT LEARNERS CAN LEARN

### Changes

ADD GIT AND GITHUB LEARNING TRACK

### Full Name

MEET SHAH

### Participant Role

CONTRIBUTER

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

**Comment by Meetpidev** [comment]
@rishicds Can i work on this ?

**Comment by rishicds** [comment]
assigned,follow code structure, if you run into any issues ask @pratheekv39

**Comment by Meetpidev** [comment]
@rishicds Please Review PR..

**Comment by Meetpidev** [comment]
@rishicds Plrease Review PR..
