### ISSUE TITLE
Updation of Navbar

### ISSUE THREAD

**Issue by Shariq2003** [GDSC-RCCIIT/gdg-website#48]
As I am working on the routing of the website, I have seen the navbar contains useless links and options and also not appropriate

![image](https://github.com/user-attachments/assets/8268189b-90f4-43d9-a8bc-179537b3a66d)

![image](https://github.com/user-attachments/assets/271c1bc9-08c8-4184-b4e8-3f34188a62b0)

![image](https://github.com/user-attachments/assets/c744500f-ca4e-4786-bb97-7225b39e1edb)

![image](https://github.com/user-attachments/assets/aa520940-6858-424f-a15f-e0b2e0adefbc)

I want to update the navbar as I also have to manage the routing that's why I am thinking of implementing that too.

PS : In the SS, I have also added an landing page, for which I have also raise an issue, also please assign that to me.

**Comment by rishicds** [comment]
assigned @Shariq2003
