### ISSUE TITLE
 Implement JSON Server for Temporary Data Loading on GDG 

### ISSUE THREAD

**Issue by Shariq2003** [GDSC-RCCIIT/gdg-website#493]
Since the GDG college site currently has multiple pages but no external data source, we need a temporary solution to display content. To address this, we will implement a JSON server to act as a temporary data folder. This server will allow us to simulate API data and dynamically load content onto various pages as needed. Multiple PRs will be attached to this umbrella issue for implementing and integrating the JSON server into specific pages.

**Multiple PR's will be raised attaching this issue, with the permission of PA**

**Comment by rishicds** [comment]
Granted and assigned
