### ISSUE TITLE
🧑‍💻: create forgot password page

### ISSUE THREAD

**Issue by AyushSharma72** [GDSC-RCCIIT/gdg-website#499]
### Title

i want to create  a forgot password page 

### Enhancement Aim

i want to create  a new page forgot password 

### Changes

add a new page

### Screenshots 📷

![image](https://github.com/user-attachments/assets/40990d15-c9c1-4715-b4c3-c5e9ebdb2c8b)
this page do not exist

### Full Name

Ayush sharma

### Participant Role

gssoc-ext

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

**Comment by rishicds** [comment]
Assigned

**Comment by Meetpidev** [comment]
@rishicds can i work on it as i already worked before..

**Comment by rishicds** [comment]
> @rishicds can i work on it as i already worked before.. on the same issue

Has been assigned to @AyushSharma72
