### ISSUE TITLE
Create a Responsive Homepage for GDG RCCIIT Website

### ISSUE THREAD

**Issue by master-ginger** [GDSC-RCCIIT/gdg-website#5]
Description: The current homepage of the GDG RCCIIT is not developed yet. I would like to create it and benefit it from enhanced responsiveness

Proposed Solution: I would like to implement a responsive homepage with the following approaches:
1. Utilize Tailwind CSS's responsive utility classes (e.g., sm:, md:, lg:, etc.) to adjust layouts for various screen sizes.
2.  Create a mobile-first layout, ensuring the page scales well across devices.
3. Improve navigation, typography, and element spacing with Tailwind's utility classes to ensure readability and usability on smaller screens.

I would be happy to work on this and submit a pull request. Let me know if there are any design specifications or additional functionality to consider!

**Comment by rishicds** [comment]
Hello, what kind of design do you have in mind? Can you share any templates? @master-ginger

**Comment by master-ginger** [comment]
I liked the below template. I could make changes according to the content that needs to be added. Please let me know if you can assign me this task
https://www.adfolio.design/landing-pages/6hydjnn3pruiz2z?from=lp-archive

**Comment by rishicds** [comment]
wow this seems great, build something similar, assigned @master-ginger

**Comment by rishicds** [comment]
any update @master-ginger

**Comment by master-ginger** [comment]
Yes I'm working on it will share the updates soon

**Comment by master-ginger** [comment]
Started with catchy phrase and event section for laptop and mobile screens. Do let me know if any changes or additional content is required
![Screenshot 2024-10-15 231633](https://github.com/user-attachments/assets/98fda8a3-5a83-4ab6-b7d4-fa78df38a318)

![image](https://github.com/user-attachments/assets/2186dfa7-756b-4f60-9d7a-4664bee35add)

**Comment by rishicds** [comment]
nice @master-ginger , continue

**Comment by rishicds** [comment]
@master-ginger please give a PR today if possible

**Comment by master-ginger** [comment]
Some parts are remaining can I complete those and then make a PR

**Comment by rishicds** [comment]
okay but give a pr today positively @master-ginger

**Comment by master-ginger** [comment]
I have made a pull request please check and let me know
