### ISSUE TITLE
Addition of Augmented Reality (AR) / Virtual Reality (VR) Development Roadmap

### ISSUE THREAD

**Issue by pratheekv39** [GDSC-RCCIIT/gdg-website#516]
@rishicds GSSOC is coming to an end . I just thought of making one last issue before the event ends today at 7 p.m . Kindly , assign this issue to me and accept the PR before 7 p.m .
I genuinely appreciate your support and responsiveness throughout the program, as it’s made the process incredibly rewarding. Thank you for being so actively involved and for facilitating each contribution. It’s been an amazing experience, and I’m grateful for everything.
Thank you :)

**Comment by rishicds** [comment]
Hi, it was a great experience working with you too! Thank you for adding so many helpful roadmaps and in such great detail!

**Comment by dev129** [comment]
Hi @pratheekv39  , i think the AR/VR roadmap is already present:
![image](https://github.com/user-attachments/assets/76679afa-96ac-4ce6-b677-7719d5ed06a9)
So you change to something other.
