### ISSUE TITLE
🧑‍💻:  PYTHON LEARNING TRACK

### ISSUE THREAD

**Issue by Meetpidev** [GDSC-RCCIIT/gdg-website#521]
### Title

PYTHON LEARNING TRACK

### Enhancement Aim

TO LEARN PYTHON

### Changes

PYTHON LEARNING TRACK

### Full Name

MEET SHAH

### Participant Role

CONTRIBUTER

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

**Comment by Meetpidev** [comment]
@rishicds AS THERE IS ML LEARNING TRACK BUT NOT PYTHON LEARNING TRACK.. WE SHOULD INCLUDE IT

**Comment by rishicds** [comment]
Assigned

**Comment by Meetpidev** [comment]
@rishicds Please review PR before GSSoc finifhing time
