### ISSUE TITLE
SignUp/SignIn Logic Implementation Along with UI Enhancement of Both Pages

### ISSUE THREAD

**Issue by Shariq2003** [GDSC-RCCIIT/gdg-website#53]
https://github.com/user-attachments/assets/4013e22e-48a6-41e3-a37a-1309a0c35b30

https://github.com/user-attachments/assets/2997755f-3a60-4460-a756-568facd1e13e

I want to implement signing and signup logic along with UI Enhancments

**Comment by inkerton** [comment]
This has already been addressed They haven't decided on a database yet so You cannot have logic until a DB is decided.

**Comment by Shariq2003** [comment]
> This has already been addressed They haven't decided on a database yet so You cannot have logic until a DB is decided.

I am going to implement the logic in frontend, not in backend

**Comment by rishicds** [comment]
ok but make sure it works with firebase or supabase @Shariq2003
