### ISSUE TITLE
[Bug]: Solving the theme Bug

### ISSUE THREAD

**Issue by inkerton** [GDSC-RCCIIT/gdg-website#57]
![image](https://github.com/user-attachments/assets/2221c2a7-3ab4-43ac-b88b-db5ed8900b38)

I am not sure whose PR you merged which disrupted the whole color texture of the website It was simple white for now but now It is like this and This is not a dark theme. 
Since I checked and there are no dark themes or toggle buttons merged. 

@rishicds assign this to me I will check it out and correct it.

**Comment by Shariq2003** [comment]
@inkerton i have already raised an issue for this.

**Comment by inkerton** [comment]
Not talking about navbar here Read understand then comment. @Shariq2003

**Comment by Shariq2003** [comment]
> Not talking about navbar here Read understand then comment. @Shariq2003

#52, look into the video first, then try to understand me.

**Comment by rishicds** [comment]
assigned @inkerton

**Comment by inkerton** [comment]
@Shariq2003 Yes buddy I saw your PR. I am not talking about the navbar or routing.

**Comment by Shariq2003** [comment]
@inkerton buddy, this issue has already been resolved.
It's the navbar issue, that I have fixed mistakenly in my Navbar implementation.
Sorry for this, as I have refined the navbar, the global.css file also sets the bg to blue, that I have removed just for my local, but mistakenly committed in My PR.

**Comment by inkerton** [comment]
Yeah saw it if you eager to solve the issue then correct the coloring of your event page then You ruined it @Shariq2003 
![image](https://github.com/user-attachments/assets/ae2cde6e-7637-4fed-ad54-3d6bba686f27)

**Comment by Shariq2003** [comment]
> Yeah saw it if you eager to solve the issue then correct the coloring of your event page then You ruined it @Shariq2003 ![image](https://private-user-images.githubusercontent.com/127668005/378125239-ae2cde6e-7637-4fed-ad54-3d6bba686f27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNzY3NTMsIm5iZiI6MTcyOTM3NjQ1MywicGF0aCI6Ii8xMjc2NjgwMDUvMzc4MTI1MjM5LWFlMmNkZTZlLTc2MzctNGZlZC1hZDU0LTNkNmJiYTY4NmYyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQyMjIwNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDNmYzM3MzI4M2Q1MTcxNWMyODYzZWRiMzM2MGZiZmYyZjU4NmRiNmFiM2VhNWU0ZmZjMmY0YjVmOGYzYWM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YyAyOwqOWEcgMPxg3WZaFoutUm8Keh-m2niEHvUBv64)

Buddy Actually, I added the events page first, then fixed the BG issue. That's why this issue occurs.
Well, I will fix this in my next PR; don't worry about it.

Thanks for letting me know about this.
