### ISSUE TITLE
UI UX Enhancements | Addition of BackToTop Button | That will facilitates the user to scroll to top easily in one Click

### ISSUE THREAD

**Issue by Shariq2003** [GDSC-RCCIIT/gdg-website#59]
That will facilitate the user to scroll to top easily in one Click
Just like the GSSOC Website

![image](https://github.com/user-attachments/assets/a6fef014-721b-4143-a5ee-83624c587866)

**Comment by rishicds** [comment]
assigned @Shariq2003

**Comment by Shariq2003** [comment]
@rishicds sir, u have not added labels to my PR
