### ISSUE TITLE
UI UX Enhancements | Service Implementaion For User's Photo Fetch by LinkedIn URL | Teams And Gallery Page Enhancement | Static User's Profile Photo | No Hover Effects 

### ISSUE THREAD

**Issue by Shariq2003** [GDSC-RCCIIT/gdg-website#61]
I want to fix the following :-

1. Static Profle photos of Users.
2. Implementation of Services that will fetch the user's profile photo from its linkedin by LinkedIn URL that will be added on the teams Page.
3. Enhancement of teams and Gallery Page.

https://github.com/user-attachments/assets/86a61bea-0bb8-4980-8213-679f24768a56

**Comment by rishicds** [comment]
assigned

**Comment by Shariq2003** [comment]
@rishicds sir, could u please increase the level as I am going to implement the service.

**Comment by rishicds** [comment]
Oh sorry I meant to give 3

**Comment by Shariq2003** [comment]
> Oh sorry I meant to give 3

Ookk, np sir
Thanks alot

**Comment by Shariq2003** [comment]
@rishicds I am having issues in the service implementation of  LinkedIn User Profile Photo Fetch by LinkedIn Profile Link as the LinkedIn policies are now a bit changed that require the OAuth as a member by their Profile_IDs. For which we have to gather all the members' LinkedIn Profile_ID, along with the visibility option enabled by them, which makes this service implementation a bit tough for the management team of you (in future).



That's why, for now, I am going to implement the modular approach to store the team's data in a separate file that can be easily manageable, along with the UI Enhancements for better UX.
