### ISSUE TITLE
Feat: to improve customer retention and drive more traffic to the website by offering incentives like upcoming events, workshops, meetups etc.

### ISSUE THREAD

**Issue by dev129** [GDSC-RCCIIT/gdg-website#66]
### Overview
The aim is to enhance user engagement and boost website traffic for the GDG on Campus RCCIIT website by offering interactive features like alerts, popups, and notifications. These features are designed to promote community events, provide exclusive deals, and keep users updated about GDG activities, fostering a stronger connection with the community.

### Key Features

1. **Event Announcements :** Regular updates on "Event of the Day," "Upcoming Workshop," or special offers for GDG events. These notifications will keep users informed and encourage active participation.
   
2. **Email Subscription for Updates:** Add an email subscription option in the website's footer along with a notification feature, enabling users to subscribe for event updates, exclusive content, and community announcements.

3. **Dedicated WhatsApp Group for Updates:** For users who may not prefer traditional social media platforms like Instagram, Discord, or Telegram, we will offer a WhatsApp group link in the footer specifically for event and deal updates, focusing on better engagement with all community members.

What's your say @rishicds ?

**Comment by rishicds** [comment]
Assigned! @dev129

**Comment by dev129** [comment]
**Hey there @rishicds !**
![image](https://github.com/user-attachments/assets/1a3ca031-82d8-4d77-813c-cd12336e9473)
This is the wireframe of what I shall be making for the notification.

Just a quick note: I’ve been working on some updates, and I’ve decided to break down the task into three separate issues instead of merging everything into one. This way, it’ll be easier to manage each part individually. Trust me, it’ll save both of us some hassle down the line when things get more complex. 

Hope that’s okay with you! I just think it'll make the workflow a bit smoother.

Thanks! Let me know if that works for you.

**Comment by dev129** [comment]
@rishicds shall I start designng it ?

**Comment by dev129** [comment]
Hello @rishicds , are you still there ?

**Comment by rishicds** [comment]
yes start @dev129 , its okay you dont have to ask each time

**Comment by dev129** [comment]
Yeah, its just that I am a beginner in OSS , still tryin to figure out things.

**Comment by dev129** [comment]
https://github.com/user-attachments/assets/b41e0567-b038-49d1-ac04-389652e45753

Hi @rishicds , I have just completed the notification design, also I shall be raising and issue to redesign an issue to redesign footer, with newsletter subscription with a new deisign you might like.

**Comment by dev129** [comment]
Hello @rishicds , are you still there ?

**Comment by rishicds** [comment]
Hi , sometimes I am inactive, you don't have to worry, if you have finished give pr I will merge it if everything is okay

**Comment by rishicds** [comment]
> This is okay you can give pr
