### ISSUE TITLE
want to add dark and light mode toggle 

### ISSUE THREAD

**Issue by sv410** [GDSC-RCCIIT/gdg-website#7]
I'm always frustrated when browsing websites or applications without the option to switch between dark and light modes. The lack of this feature often leads to eye strain, especially in low-light environments, and reduces the overall user experience.

Describe the solution you'd like I propose implementing a dark and light mode toggle on our website. This feature would allow users to easily switch between dark and light themes based on their preference or environment. It enhances the user experience by providing a comfortable viewing option in different lighting conditions.

Describe alternatives you've considered

Manual CSS Switch: Manually change the CSS files for dark and light modes, but this approach is cumbersome and not user-friendly.

Browser Extensions: Relying on browser extensions for dark mode, but this isn't consistent acro
![WhatsApp Image 2024-10-12 at 6 03 50 PM](https://github.com/user-attachments/assets/bfdcaa93-7f8c-420f-8894-a7e54d66f421)
ss all users and browsers.
![WhatsApp Image 2024-10-12 at 6 02 58 PM](https://github.com/user-attachments/assets/cd5b82b9-c936-4cd9-95a3-f933c3a595eb)

JavaScript Libraries: Use a third-party JavaScript library for theme switching, but this can be overkill for a simple feature.

Additional context Implementing a dark and light mode toggle using HTML and CSS will significantly improve the usability of our website

**Comment by rishicds** [comment]
Use a more unique button if you can, assigned

**Comment by sv410** [comment]
@rishicds 
![WhatsApp Image 2024-10-13 at 1 57 57 PM](https://github.com/user-attachments/assets/ac6a637c-aa1f-4903-9d57-5fd377524de6)
![WhatsApp Image 2024-10-13 at 1 57 25 PM](https://github.com/user-attachments/assets/604a0019-6be3-40be-a698-d5115b1d98d3)
is this fine?

**Comment by rishicds** [comment]
> @rishicds 
> ![WhatsApp Image 2024-10-13 at 1 57 57 PM](https://github.com/user-attachments/assets/ac6a637c-aa1f-4903-9d57-5fd377524de6)
> ![WhatsApp Image 2024-10-13 at 1 57 25 PM](https://github.com/user-attachments/assets/604a0019-6be3-40be-a698-d5115b1d98d3)
> is this fine?

Yes,this is nice

**Comment by sv410** [comment]
will update u after i am done with my work! pls update the level if u liked my work!

**Comment by sv410** [comment]
@rishicds can u pls check and pls update the level if u liked it!

**Comment by rishicds** [comment]
The pull requests are on your repo not this one, also please make it a React Component, and make it one single pull request @sv410

**Comment by sv410** [comment]
@rishicds will work on and update! pls add level 3 and hacktoberfest

**Comment by rishicds** [comment]
this repo is not a part of hacktoberfest @sv410
