### ISSUE TITLE
Redesign footer with features

### ISSUE THREAD

**Issue by dev129** [GDSC-RCCIIT/gdg-website#72]
Hi @rishicds ,

I was recently working on the offers section of your website when something interesting caught my eye: the footer section could be much more engaging and impactful. Since the footer is visible on almost every page, it’s a perfect opportunity to capture more attention, build trust, and even drive additional actions from users. With a few carefully designed tweaks, we can make it more engaging, user-friendly, and add valuable features that will benefit your overall website experience.

I’d love the chance to redesign this section for you. I have some fresh ideas that will enhance how users interact with the footer and keep them engaged throughout their visit.

**Comment by rishicds** [comment]
assigned

**Comment by dev129** [comment]
Hi @rishicds , design is completed , here is the final look but still some changes are to be done from your side before PR launch .
![image](https://github.com/user-attachments/assets/d0f3ebd0-9516-410e-bff5-bf7f00cde8b6)

**Comment by dev129** [comment]
Hi @rishicds , shall I launch it now ?

**Comment by rishicds** [comment]
Yes you can give pr @dev129

**Comment by dev129** [comment]
Done @rishicds please check .
