### ISSUE TITLE
Redundant Data in Landing Page | Refinement and Enhancment of Landing page 

### ISSUE THREAD

**Issue by Shariq2003** [GDSC-RCCIIT/gdg-website#74]
Refer to this Video:-

https://github.com/user-attachments/assets/9fc6dfae-59e2-4aea-b31f-680975c2d83b

Issues :-

1. Redundant data present on the Landing page like : 
    - Events (For which a dedicated page is already there), 
    - Projects (For which a dedicated page is already there)
    - About (For which a dedicated page is already there)
    - Team members (For which a dedicated page is already there)
2. Now there is only a single section left which does not contribute to redundancy. i.e., Welcome Section. that's why I have add more data to landing page.
3. Enhance the UI and UX.

**Comment by rishicds** [comment]
Assigned
