### ISSUE TITLE
Side Scrollbar Customisation | That will match with the Theme of the Website 

### ISSUE THREAD

**Issue by Shariq2003** [GDSC-RCCIIT/gdg-website#75]
For the UI Enhancement, we have two options:-

1. Either remove the side Scrollbar for which we have replacement by progressBar ( That I have added) or
2.  Customise the side scrollbar that will match with the website theme.

Let me know any one, and assign me this issue.

![image](https://github.com/user-attachments/assets/cfbf0734-47fa-422f-b8c2-2a82192ee402)

**Comment by rishicds** [comment]
assigned

**Comment by rishicds** [comment]
remove the scrollbar

**Comment by Shariq2003** [comment]
@rishicds sir, please add labels to my PR #70
