### ISSUE TITLE
[UI Addition]: Make a Responsive header

### ISSUE THREAD

**Issue by inkerton** [GDSC-RCCIIT/gdg-website#8]
Hey @rishicds Can you provide me any basic idea of how many pages and what pages you wish to have in all?

**In Header and in Footer** also. 

If you have any inspiration of how You want the website to look like ??

**Comment by inkerton** [comment]
Tell me a bit about your requirements and please assign the issue to me I will work on this. @rishicds 

Please also add the tags to the issue.

**Comment by inkerton** [comment]
I will be making a header with:- 
About
Chapters
Upcoming Events
Login
Signup

**Comment by rishicds** [comment]
hello @inkerton , this issue is already being worked on on #3 , after that is merged you can work on this

**Comment by inkerton** [comment]
@rishicds It has been a week since he opened the issue and had not worked I really don't think it would be nice to hold my PRs for 3 days.

I am asking you nicely if you can tell him to work upon my already made PR. I do not wish to waste 3 days waiting when I can work a lot more in that time.

**Comment by inkerton** [comment]
@rishicds I planned to add about 5 issues and 5PRs by today itself .

Can you please not insist on keeping me waiting!
