### ISSUE TITLE
ADD a page for Careers

### ISSUE THREAD

**Issue by shubhagarwal1** [GDSC-RCCIIT/gdg-website#83]
**Purpose**: A platform for users to explore job or internship opportunities, either within the GDG community or from partner organizations.
**Features**: Job listings, filters by category or location, and a "Submit Your Resume" button.

**Comment by Shariq2003** [comment]
@shubhagarwal1, have you read the guidelines of GSSOC ?
At a time you can raise only 2-3 issues, else it will be counted towards spamming.

**Comment by Shariq2003** [comment]
@rishicds please look into this, as per the GSSOC Guidelines, a contributors can only raise 2-3 issues at a time and @shubhagarwal1 is not following the guidelines.

**Comment by shubhagarwal1** [comment]
Hey @rishicds can you please assign me this task
