### ISSUE TITLE
Multiple UI/UX Enhancements and Fixes

### ISSUE THREAD

**Issue by shubhagarwal1** [GDSC-RCCIIT/gdg-website#85]
1. Return to Home Page on Logo Click
Description: Ensure that clicking the logo on the navigation bar returns the user to the home page.
2. Add a Light Gradient Background to Events Page
Description: Implement a light gradient background on the Events page to enhance the visual appeal and improve user experience.
3. Fix Unused Footer on About Page
Description: Resolve the issue of the unused or unoptimized footer on the About page to make it more functional and visually aligned with the overall design.
4. Optimize Colors for Existing Progress Bar
Description: Adjust the colors of the current progress bar to ensure better readability and consistency with the overall theme of the application.

**Comment by shubhagarwal1** [comment]
Hey @rishicds can you please assign me this task

**Comment by rishicds** [comment]
Assigned
