### ISSUE TITLE
[Enhancement]: Add framer motion animation to Projects

### ISSUE THREAD

**Issue by inkerton** [GDSC-RCCIIT/gdg-website#92]
![image](https://github.com/user-attachments/assets/33558088-e764-40f5-8d1f-aaa227554995)

@rishicds Please assign it to me

**Comment by inkerton** [comment]
https://github.com/user-attachments/assets/ec1b0104-4833-4946-84d4-41fadc3e426f

@rishicds How does this look??

**Comment by inkerton** [comment]
OR this one @rishicds 


https://github.com/user-attachments/assets/d3dd9686-ae6e-43ef-abf3-912984734557

**Comment by rishicds** [comment]
Hi I have assigned 3 issues to you please finish them then I can assign the rest, gssoc guidelines only allow a contributor to work on 3 issues at a time.

**Comment by inkerton** [comment]
Ok @rishicds , no issues I had these 2 demos ready before I raised the issue I just needed your opinion on which one would be better. I will have all the PRs ready by Tom so as soon as you assign me the issue I will raise the PRs.
